### ISSUE TITLE
Switch off web camera when facefilter is paused

### ISSUE THREAD

**Issue by blurymind** [jeeliz/jeelizFaceFilter#101]
Whenever a web camera is used, on a lot of devices a light turns on. I want to add a on/off switch to my app, and the pause method works on stopping the tracking - but the webcamera remains on - the light is on.

I was wondering if there is some sort of a way to initialize face tracking, but keep the light off while its paused. Stop the webcamera from running when it's paused. 

if not, what is the best way to completely stop the facefilter process and reinitialize it whenever requested

**Comment by xavierjs** [comment]
Hi,

Indeed, this feature is currently not implemented in this Github repository.
However, @Jeeliz we would be happy to help you to adapt our libraries to fit your needs.
You can ask for this specific development service to contact__at__jeeliz.com and we will send you a proposal. 

Best regards,
Xavier

**Comment by blurymind** [comment]
I tried with `stream.getTracks().forEach(track => track.stop())` without much luck :(

**Comment by blurymind** [comment]
I would be able to figure it out if all of your code wasn't minified :/ 
where the heck is `b.videoStream`

**Comment by victorevox** [comment]
Hi @xavierjs , I would also like to have this feature available, I want to put the facerecognition on a modal, and when user close it , stop the recognition and at the same time dispose the user's camera, that would make the user more confident about the app really stops and they can continue navigating on the same page. From my understanding we should be able to access the source stream in order to execute some thing like 

> `player.srcObject.getVideoTracks().forEach(track` => track.stop());`

As a side note, what should be the correct approach to have the recognition in a modal, it seems that I need move the Canvas Element rather than destroy it, since we cannot initialize the JEELIZFACEFILTER twice, as it trows an error, it would be nice to be able to do that

Anyway, thanks for sharing this awesome library!

**Comment by xavierjs** [comment]
Hi @victorevox ,

I will implement the video toggle very soon, seems legit.

The side note is related to https://github.com/jeeliz/jeelizFaceFilter/issues/74 .

I guess you are looking to use the lib with React or similar. React is great, I use it too but it imposes a paradigm which does not suit to inserting a `<canvas>` with a heavy processing like a Jeeliz FaceFilter canvas. Fortunately there multiple hooks to append and take off the canvas. I don't allow to re-init the library to encourage good practice.

Best,
Xavier

**Comment by victorevox** [comment]
HI again @xavierjs , 

> I will implement the video toggle very soon, seems legit.

sounds great, I'll stay tuned for that feature

> I guess you are looking to use the lib with React or similar. React is great, I use it too but it imposes a paradigm which does not suit to inserting a <canvas> with a heavy processing like a Jeeliz FaceFilter canvas. Fortunately there multiple hooks to append and take off the canvas. I don't allow to re-init the library to encourage good practice.

Yeah, actually Im using Angular to build an embeddable application making use of Angular Elements (Web Components) , so the idea is that this component injects its own logic for displaying the modal and kicking the face-recognition inside of it, I'll try to accomplish this based on the logic of "do not re-initialize" , thanks so much 

Best, 
Victor

**Comment by xavierjs** [comment]
Hi,

If you want to submit a pull request to add a demo using a specific frontend engine like Angular you are welcome :). I don't work on these topics but I think it would be very interesting for other users.

The latest commit implement the possibility to completely stop the camera video track.
The documentation has been updated: https://github.com/jeeliz/jeelizFaceFilter#miscellaneous-methods (take a look at `JEELIZFACEFILTER.toggle_pause` method. I did not test it on many devices to I keep the issue open .

Best,
Xavier

**Comment by xavierjs** [comment]
And sorry @blurymind to not have added this feature earlier, maintaining our open libs depends a lot on how much time we have outside commercial projects (and weekends/evenings schedule) ... We do our best!

**Comment by victorevox** [comment]
Thanks @xavierjs 

> If you want to submit a pull request to add a demo using a specific frontend engine like Angular you are welcome :). I don't work on these topics but I think it would be very interesting for other users.

Sounds like a good idea, I'll try to make a light example of my use case, I'll test the new version  and provide feedback on the upcoming days

**Comment by xavierjs** [comment]
I close the issue since this feature is implemented.
Feel free to re-open it if it does not work correctly.

**Comment by blurymind** [comment]
@xavierjs no worries :) thank you for getting around to it
