### ISSUE TITLE
Vertical rotation isn't accurate on portrait canvas.

### ISSUE THREAD

**Issue by cviali** [jeeliz/jeelizFaceFilter#102]
[looking up on square canvas](https://i.imgur.com/pbTFulk.png) (720x720)
[looking up on portrait canvas](https://i.imgur.com/nJR03rQ.png) (720x1280)

as the image suggests, somehow the face filter doesn't accurately track vertical rotation on portrait canvas. Did I miss something?

**Comment by xavierjs** [comment]
It is a problem of aspect ratio.
I don't know what is your implementation but I think there is an offset between the canvas and the video.
Also when the FaceFilter canvas size is updated you should call `JEEFACEFILTERAPI.resize();` to recomputing video cropping parameters.
The best way is to use the resizer helper ( https://github.com/jeeliz/jeelizFaceFilter#canvas-and-video-resolutions ).

**Comment by cviali** [comment]
> It is a problem of aspect ratio.
> I don't know what is your implementation but I think there is an offset between the canvas and the video.
> Also when the FaceFilter canvas size is updated you should call `JEEFACEFILTERAPI.resize();` to recomputing video cropping parameters.
> The best way is to use the resizer helper ( https://github.com/jeeliz/jeelizFaceFilter#canvas-and-video-resolutions ).

Thank you very much for your fast reply, but what if I set the canvas size from the canvas attribute such as:
`<canvas id="jeeFaceFilterCanvas" width="720" height="1280"></canvas>`

Because this happens when I change it from the HTML not changing it when the filter is running.
is there something I should configure as well on the jeeliz's API ?

**Comment by xavierjs** [comment]
it is not enough to change it from the HTML, you have to call the `resize` method too.
It is all explained in the readme and you can also look at the code of the resize helper.

**Comment by cviali** [comment]
> it is not enough to change it from the HTML, you have to call the `resize` method too.
> It is all explained in the readme and you can also look at the code of the resize helper.

What if the canvas are already set at 720x1280 (portrait) before initialization? Is there any configuration that I miss that still have values optimized for square canvas? Because it tracks my face accurately when I set the canvas as square.

BTW though, all I have to do to use jeeliz's resize method is to initialize the facefilter inside of `JeelizResizer.size_canvas()` callback right?

**Comment by xavierjs** [comment]
There are some provided demos with canvas which are not square like the "matrix demo" (https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/threejs/matrix). The Resizer helper should handle the resizing without having to call directly FaceFilter methods.

**Comment by cviali** [comment]
> There are some provided demos with canvas which are not square like the "matrix demo" (https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/threejs/matrix). The Resizer helper should handle the resizing without having to call directly FaceFilter methods.

Thanks. BTW, is there any alternatives for getContext("2d").drawImage(); ? because getContext("2d") on jeeFaceFilterCanvas returns null.

**Comment by xavierjs** [comment]
Yes, because this canvas is already bound with a WebGL context. You cannot bound a canvas both with WebGL and canvas2D context. But if you want to draw stuffs with canvas2D you can append a second canvas overlaying the video. There are some canvas2D demos provided too.

**Comment by cviali** [comment]
Great, I got it figured out, one last thing though, I tried to use maxFacesDetected to allow multiple face tracking, everything went fine and it detects even though it's kinda hit or miss. The question is, how to remove all of the cloned 3D Mesh to each faces? for 1 face detection I'll usually just do `threeStuffs.faceObject.remove(MESHNAME)` but it seems like faceObjects doesn't have a `remove()` function. Is there anyway to have similar functions to `threeStuffs.faceObject.remove(MESHNAME)` but with multiple faces detection enabled?

**Comment by xavierjs** [comment]
Hi,

I strongly advise to use the THREE.JS helper `JeelizThreejsHelper.js` for multiface detection.
This boilerplate demo use it: https://jeeliz.com/demos/faceFilter/demos/threejs/multiCubes/
code here: https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/threejs/multiCubes

This helper will toggle the visibility of the THREE.JS objects instead of removing/adding the object from the parent. It is safer like that because if you add/remove objects you change the scene graph and maybe the 3D engine will recompile shaders/recompute more stuffs than if you just play with the visible flag.

**Comment by cviali** [comment]
> I strongly advise to use the THREE.JS helper `JeelizThreejsHelper.js` for multiface detection.

Well, I'm pretty curious about this code that will clone the filters to each detected faces:
`threeStuffs.faceObjects.forEach(function(faceObject){
        faceObject.add(threeCube.clone());
    });`

Not actually disregarding your advice to use Jeeliz's THREE.JS helper script though, but how does that forEach function actually work and why I can't just do like `threeStuffs.faceObjects.remove(MESHNAME)` ?

And is there any requirement in order to get good result when using multiface detection?, because it seems like it hardly ever detects the second face on lower-end devices.

**Comment by xavierjs** [comment]
The performance is adaptative, so on lower end devices won't be able to do as many detection per second and the result will be worse.

threeStuffs.faceObjects is an instance of JavaScript array so you can use forEach (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach).
remove() is not a method of JS array.
Each item of this array is an instance of a THREE.Object3D or THREE.Mesh. You may use remove then.
