### ISSUE TITLE
Very slow in detecting face..

### ISSUE THREAD

**Issue by iamappmaker** [jeeliz/jeelizFaceFilter#103]
This is awesome library and i had tested all the features and i decided to create a app but problem is face detection is very slow. 
I love the face replacement in GIF. The main problem is GIF Quality is very less and also high in size.
Is it possible to do face replacement in video, though size is high in video, it will be good.

Final problem is after completing everything i can't able to save it either GIF or Video. 
There are 2 canvas, all the plugin available has option for selecting only one canvas.

**Comment by xavierjs** [comment]
What is your configuration, screen resolution canvas size.... It is very fast with Iphone6, Iphone X, Samsung S7, Huawei P9, ... if it is implemented correctly: with a reasonnable canvas resolution and an app which does not use too many resources.
It is possible to do face replacement in video, as the code is provided you can tweak it as you want.
But then you cannot save the built gif, there are already some issues about it:
* https://github.com/jeeliz/jeelizFaceFilter/issues/66
* https://github.com/jeeliz/jeelizFaceFilter/issues/27
