### ISSUE TITLE
load_NNC is not defined in es6 module, when including NNC.json content directly

### ISSUE THREAD

**Issue by georginio** [jeeliz/jeelizFaceFilter#105]
I'm trying to implement filter but receiving error

![Screenshot from 2019-07-19 13-41-59](https://user-images.githubusercontent.com/8328003/61531099-eea11200-aa36-11e9-84d1-ec27a5bdb9b4.png)

```
import jeelizFilter from './lib/jeelizFaceFilterES6.js'   
import nnc from './lib/NNC.json'  
export default canvas => {    
    return jeelizFilter.init({
        canvas: canvas,
	NNC: nnc,
        //callbacks...
    })
}
```

**Comment by xavierjs** [comment]
Hi,

It should work now, please confirm.
Thanx for the reporting,

Best,
Xavier

**Comment by georginio** [comment]
Hi Xavier, 

It isn't showing NNC error anymore, but now I get 
`ERROR in ContextFeedForward :  WebGL is not enabled`
WebGL is enabled in my browser, other demos working fine. 
_Maybe this is not related._

**Comment by xavierjs** [comment]
Hi @georginio 

Are you sure `canvas` is well defined, is a `<HTMLCanvasElement>` and has not been bound to another context before (either WebGLContext or standard 2D context)?
Does the boilerplate work? https://jeeliz.com/demos/faceFilter/demos/threejs/cube/
What is your browser and OS ?
Can you submit a screenshot of https://webglreport.com/?v=2 and https://webglreport.com/?v=1

Thanx

**Comment by georginio** [comment]
Hi @xavierjs, 

I was binding canvas with other context. It works now. Sorry for late answer

Thanks
