### ISSUE TITLE
how to get center point between two eyes. (In all the cases including head rotate, left or right turn)

### ISSUE THREAD

**Issue by vasanthhr** [jeeliz/jeelizFaceFilter#106]
Hello,

Hope you are doing good.

I could see in your post saying, face detection output as  `"The detection is centered on the point between the 2 eyes."` 

i seen these points as output from detected state:` x,y other values. (width,  height with respect to canvas).`

can you please guide me how to calculate the center point between two eyes. (I need center point between two eyes for all cases including, left side turn or right side turn or head rotation ).

**Comment by xavierjs** [comment]
Hi,

The neural network is trained with faces centered on the point between the 2 eyes. However this information is not available directly.

You can start from the glasses VTO demo ( https://jeeliz.com/demos/faceFilter/demos/threejs/VTO/ and code here: https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/threejs/VTO).
You take the point in 3D between the 2 eyes in the 3D glasses model and you project it to get the point centered between the 2 eyes using projectionMatrix and worldMatrix.

If you need to compute more accurately the position of specific face landmarks (for earring virtual tryon, makeup virtual tryon) we can provide this kind of development service, and we have a more advanced version of this library (FaceFilterLM), but it is not released publicly. In this case we can train a specific neural network providing the position of facial landmark among its outputs. You can contact us here: https://jeeliz.com/contact-us/ or by email at contact__at__jeeliz.com for for information.

Best regards,
Xavier Bourry

**Comment by vasanthhr** [comment]
@xavierjs 

Assume, I am able to get the centered point from a 3D model once face-model placed into detection box with proper pose direction. (By default pre-defined and known centered point in 3D model). Is this sufficient way to get the centered point between 2 eyes?.

(Note: I need just 2D coordinates for this centered point between 2 eyes. I really don't need 3D centered point).

 I didn't get your statement :: ` you project it to get the point centered between the 2 eyes using projectionMatrix and worldMatrix.`  Why I need to calculate this projectionMatrix and worldMtrix. 
(If I need to calculate then please guide me how to do, I didn't see these matrix calculation anywhere in threejs/VTO folder you shared).

(Sure, I do have your email id, I will reach you for anything needed regarding LM).

**Comment by xavierjs** [comment]
Hi,

Even if you need 2D coordinates, it involves 3D operations. Before working with 3D I advise you to learn some stuffs il 3D programming: projection/movement matrix, mesh rendering, ... You can find plenty of good tutorials and doc on the Internet (here for example: http://www.webglacademy.com ) .

Best
