### ISSUE TITLE
NPM update

### ISSUE THREAD

**Issue by MaciejWWojcik** [jeeliz/jeelizFaceFilter#109]
Hello, 
I want to ask if you plan to update the npm package. The last one was updated 7 months ago and when I compared the `jeelizFaceFilter.js` it seems that they are very different. 

Could you please update this package? I'm using this in one of my projects as npm dependency and this will help me a lot. 

Thanks!

**Comment by xavierjs** [comment]
Hi,

I have updated the NPM package ( https://www.npmjs.com/package/facefilter ).
Also I have removed the `/demos` and `/libs` paths from the NPM release (it makes the package lighter).

Best,
Xavier

**Comment by MaciejWWojcik** [comment]
thanks!
