### ISSUE TITLE
Delay compensation, between webcam input and 3D model

### ISSUE THREAD

**Issue by neheren** [jeeliz/jeelizFaceFilter#110]
**A feature request**
In order to get closer to more state of the art implementation like Snapchat, Instagram, etc. (no offence ;) ) You could make up for the delay between the 3D model and the actual webcam output; 
As of now, the 3D model is shortly 'slower' or behind the webcam output. By delaying the webcam canvas output just slightly (1 or 2 frames) without delaying the 3D model, it would result in a much more realistic tracking, since the 3D model would 'stick' more to the the face.

**Solution**
The feature should preferably set be default, but still optional. With an init argument like delay_compensation measured in frames.

I hope this makes sense!

Sincerely Nikolaj

**Comment by xavierjs** [comment]
This delay depends on the hardware capability.

If the hardware is good, then we can do a lot of detection per frame (up to 7) and the 3D model will stick to the face. If the hardware is less good, then we will do only 3 detections per second.
If you are using and old neural network model (like `NNCIntel1536.json` in https://github.com/jeeliz/jeelizFaceFilter/tree/master/dist , the one which is working with Intel Iris 1536 GPU) for example it is less efficient than new ones unfortunately.

The output of a neural network is always noisy, so we need to stabilize it. This stabilization can set a delay between tracking and the video frame, especially if we cannot do many detections per second. You can try to lower the stabilization settings. The doc is here https://github.com/jeeliz/jeelizFaceFilter#miscellaneous-methods  (look for `JEEFACEFILTERAPI.set_stabilizationSettings` ). You can try this for example:

```
JEEFACEFILTERAPI.set_stabilizationSettings({
translationFactorRange: [0.001, 0.003], //default [0.0015, 0.005]
rotationFactorRange: [0.002, 0.01], //default: [0.003, 0.02]
qualityFactorRange: [0.92, 0.98], //default: [0.9, 0.98]
alphaRange: [0.1, 1], //default: [0.05, 1]
});
```

translationFactorRange -> reduce stabilization when a face translation movement is detected
rotation: same for rotation
quality: same for detection quality
alphaRange: the second value should be 1, and the first value is how much we blend the current face detection values with the new, noisy ones when the quality of detection is the best.
 
Best,
Xavier

**Comment by xavierjs** [comment]
Hi,

I close the issue since I have provided various ways to deal with the problem.
Feel free to re-open it if you have new elements/issues related/feedbacks

Best,
Xavier
