### ISSUE TITLE
toggle_slow() throws error

### ISSUE THREAD

**Issue by mnutt** [jeeliz/jeelizFaceFilter#112]
**Describe the bug**

When calling `JeefaceFilterApi.toggle_slow(true);`, I see an error:

```
TypeError: this.Rc is not a function
```

**To Reproduce**
1. Instantiate a face filter with `JeefaceFilterApi.init()`
2. Call `JeefaceFilterApi.toggle_slow(true);`
3. See error in console.

**Expected behavior**
Expected to not throw error, but to slow down detection rate to conserve battery.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 69.0b14

**Additional context**
It looks like this may just be a minification problem; I don't see anywhere that `Rc` is defined and the minifier seems to otherwise not use `this` at all.

**Comment by xavierjs** [comment]
Hi,

Thank you for this detailed bug report.
It should work now, I have just pushed a fix.

Best,
Xavier

**Comment by xavierjs** [comment]
I close this issue since it should be resolved. Feel free to re-open it if there is still a problem :)
