### ISSUE TITLE
Mirror face filter in WebGL rather than using CSS

### ISSUE THREAD

**Issue by mnutt** [jeeliz/jeelizFaceFilter#113]
**Is your feature request related to a problem? Please describe.**
In face-filter mode, users expect a mirrored camera image to have a good experience. The front-facing camera doesn't do this by default, so we resort to a css transform to flip the image. This makes it more difficult to take a photo, since the photo must then be flipped via canvas, any overlaid text must be flipped in three.js so that it can be flipped back, and so forth.

**Describe the solution you'd like**
We can flip the video in the WebGL shader instead.

**Describe alternatives you've considered**
(continue using css transforms to flip)

**Additional context**
We might be able to do it in the shader like so:

```
attribute vec2 a0;
uniform mat2 u34;
varying vec2 vv0;
void main() {
  gl_Position = vec4(a0, 0., 1.),
  vv0 = vec2(.5, .5) + u34 * a0 * vec2(-1.0, 1.0);
}
```

(with `vec2(-1.0,1.0)` doing the horizontal flip)

**Comment by mnutt** [comment]
And we can check for `facingMode==="user"` to ensure it doesn't happen on the rear-facing camera.

**Comment by xavierjs** [comment]
Hi,

Thanx for this suggestion.
I will implement it as a toggable option to make it switchable easily.

Best,
Xavier

**Comment by xavierjs** [comment]
Since the last commit, you can flip the image horizontally:
* either at initialization, using `flipX: true` (see https://github.com/jeeliz/jeelizFaceFilter#optionnal-init-arguments)
* either dynamically, using `JEEFACEFILTERAPI.set_videoOrientation(0, true)` method (see https://github.com/jeeliz/jeelizFaceFilter#miscellaneous-methods )

Best,
Xavier

**Comment by xavierjs** [comment]
I close this issue since it should be resolved. Feel free to re-open it if there is still a problem :)
