### ISSUE TITLE
Specification for creating a new face filter

### ISSUE THREAD

**Issue by dineshBD** [jeeliz/jeelizFaceFilter#120]
Hi Xavier, 
I want to know what is the process of creating a new face filter. For eg, a sample exists of a tiger face filter, suppose I want to do a similar one but with a different animal like a lion or zebra, how would I approach this? Thanks.

**Comment by xavierjs** [comment]
Hi Dinesh,

We have done tutorials and linked them from the readme here: https://github.com/jeeliz/jeelizFaceFilter#articles-and-tutorials
Then if you require 3D training, there are many tutorials about how to use THREE.js.
You need some knowledge in 3D programming before being comfortable with creating face filter and it would be better to start with only 3D programming.

Best,
Xavier

**Comment by dineshBD** [comment]
Thanks mate I'll check it out.

**Comment by dhaiduk** [comment]
Hi, I want to use my geometry. Where can I find the OpenGL Shading Language tutorial on enlarging and shifting eyes or something similar?
