### ISSUE TITLE
No face detection in web page running on Android Chrome landscape

### ISSUE THREAD

**Issue by rsaville** [jeeliz/jeelizFaceFilter#124]
**Describe the bug**
My web page runs properly when the cell phone is in portrait mode. When I turn the cell phone to landscape jeelizFaceFilter no longer detects faces. Refresh of the page does not help.  I have added followZRot: true to the init call but it does not have any effect.

**Comment by xavierjs** [comment]
I have added a fix.
The jeeliz THREE.js helper call `JEEFACEFILTERAPI.resize()` to set stuffs correctly.
On most demos there is still some CSS to change because it stretches the canvas but it is easy to do.

**Comment by xavierjs** [comment]
I close the issue since a fix was implemented.
Feel free to re-open it if it does not make the job.
