### ISSUE TITLE
add new object 

### ISSUE THREAD

**Issue by hazmaniameur** [jeeliz/jeelizFaceFilter#125]
hi, 
can we add our own object, for example i work in the telecommunication domain, and i whould like to add objects like network equipments 

thank you

**Comment by xavierjs** [comment]
Hi,

I don't understand your question, please detail more. What object? The detected one like the face? Or the displayed one?

Best,
Xavier

**Comment by hazmaniameur** [comment]
hi @xavierjs 

Thank you so mush for your quick answer, 

other than faces, can the library reconize objects 

May be with an example sould be better, i have equipement like a wifi router, 

i would like to redirect my employes to my own wikipedia page, to provide them technical informations about the equipement, like how to configure it, 

Is it possible to add objects in the library, like routers, switches, power supply bar, .... 

Thank you :)

**Comment by xavierjs** [comment]
I close the issue since it is not really related to this library but to Jeeliz AR ( https://github.com/jeeliz/jeelizAR ) . Feel free to open an issue for generalistic object detection on JeelizAR repository.

Best,
Xavier
