### ISSUE TITLE
Sometimes the face-tracking lands on the nose instead of the eyes.

### ISSUE THREAD

**Issue by neheren** [jeeliz/jeelizFaceFilter#127]
**Describe the bug**
The facial recognition sometime sees the nose as being the eyes - It is kind of silly.

**To Reproduce**
Sometimes happens - but mostly triggered by bad lighting and having the camera view in frog perspective 

**Expected behavior**
Sometimes the tracking will land on the nose.

**Screenshots**
Haha...
![image](https://user-images.githubusercontent.com/15888906/65518248-4b5ff380-dee4-11e9-86f0-d1941e13069b.png)

**Additional context**
The problem might be fixed by having a kind of **size-threshold** for the facial-tracking, removing the posibilty of tracking 'faces' smaller than e.g. 20% of the screen.

**Comment by xavierjs** [comment]
Hi,

Thanx for this detailed bug report.

This option is already implemented: https://github.com/jeeliz/jeelizFaceFilter#miscellaneous-methods
it is the `scanSettings.minScale` parameter. You can either set it at initialization or call `JEEFACEFILTERAPI.set_scanSettings` to set it.

The default value is `0.15` which means that the minimum scale of the detected face is 15% of the video width. You can try to increase it to `0.25`.
Another way to avoid this would be to increase the `detectionThreshold` parameter specified in the THREE.js helper https://github.com/jeeliz/jeelizFaceFilter/blob/master/helpers/JeelizThreejsHelper.js
The current value is `0.75`. By increasing it to `0.85` for example (it should be less than `1`) the detection will be harder and may exclude more easily false positives.

Best,
Xavier

**Comment by neheren** [comment]
Nice! Thank you so much! I will close this issue.

**Comment by xavierjs** [comment]
Hello,

What exactly solved you issue? Increasing `minScale` or `detectionThreshold` or both? It can be useful for other users ;) .

Best,
Xavier

**Comment by neheren** [comment]
I did both. Also i removed the margins around the detection area, since sometimes the nose would be the only 'face-looking' object in there, which would cause the tracker to regonize it.

**Comment by neheren** [comment]
The parameters borderWidth and borderHeight

**Comment by xavierjs** [comment]
Thanx for your feedback :)
