### ISSUE TITLE
Doesn't work for Safari (desktop or iOS). Getting 'Webcam Unavailable' Error.

### ISSUE THREAD

**Issue by pkpp1233** [jeeliz/jeelizFaceFilter#13]
**Describe the bug**
I'm unable to run jeeliz face filter on safari. I'm getting the `'webcam_unavailable'` error.

**To Reproduce**
1. Go to https://jsfiddle.net/jeeliz/2p34hbeh/
2. Open command line to see error.

**Expected behavior**
You should see the camera, but you're only seeing a blank page.

**Screenshots**
![image](https://user-images.githubusercontent.com/865389/40696084-338f6674-6392-11e8-82f3-69afc6a38fef.png)

**Desktop (please complete the following information):**
 - OS: iOS / macbook pro
 - Browser: Safari

**Smartphone (please complete the following information):**
 - Device: iPhone.
 - Browser: Safari mobile.

**Comment by pkpp1233** [comment]
Looks like a recent push broke this lib for safari. A previous version ended up working for me https://jeeliz.com/demos/faceFilter/dist/jeelizFaceFilter.js so I'm using that.

**Comment by xavierjs** [comment]
You are right, the https://appstatic.jeeliz.com/faceFilter/jeelizFaceFilter.js was not the right one, the bug is fixed now
