### ISSUE TITLE
Can't start tracking in Firefox

### ISSUE THREAD

**Issue by newgamer-c1** [jeeliz/jeelizFaceFilter#130]
**Describe the bug**

JEEFACETRANSFERAPI.init in Firefox raises error as below.
```
TypeError: g is null
```

Because the Firefox's userAgent is not 'Mac OS X 10_14' but 'Mac OS X 10.14'.

<img width="598" alt="スクリーンショット 2019-10-04 15 29 22" src="https://user-images.githubusercontent.com/46787813/66186106-507b2a80-e6bc-11e9-8e71-8c2a943e4730.png">

Here is the function d() of jeelizeFaceTransferES6.js
```
return /(Mac)/i.test(navigator.platform) && ((g = navigator.userAgent) ? (g = g.match(/Mac OS X (\d+)_(\d+)/), g = 3 > g.length ? !1 : [parseInt(g[1], 10), parseInt(g[2], 10)]) : g = !1, g && 10 === g[0] && 15 === g[1]) ? !0 : !1
```

g = g.match(/Mac OS X (\d+)_(\d+)/) is null in the Firefox.
Please change checking logic.
ex)
```
g = g.match(/Mac OS X (\d+)_(\d+)/)
```
↓
```
g = (g.match(/Mac OS X (\d+)_(\d+)/) || g.match(/Mac OS X (\d+).(\d+)/) )
```
I have checked this code works.

**To Reproduce**
1. import jeelizeFaceTransferES6.js 
2. call JEEFACETRANSFERAPI.init

**Expected behavior**
JEEFACETRANSFERAPI.init raise no error in the Firefox.

**Screenshots**
<img width="358" alt="スクリーンショット 2019-10-04 15 27 02" src="https://user-images.githubusercontent.com/46787813/66186598-a1d7e980-e6bd-11e9-85ef-473de5b487be.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.4 (Mojave)
 - Browser: Firefox 
 - Version: 69.0.2 (latest)

**Comment by xavierjs** [comment]
Thank you very much for this detailed bug report. Good catch!
I have pushed a fix, I hope it will work now.

Best,
Xavier

**Comment by newgamer-c1** [comment]
I have confirmed that it works. Thank you.
