### ISSUE TITLE
Texture not loaded with glTF example 

### ISSUE THREAD

**Issue by julianlecalvez** [jeeliz/jeelizFaceFilter#133]
**Describe the bug**
I try to use JeelizFacefilter to generate new 3D model and use it. I first try the filter creation tutorial (with the luffy's hat). Unfortunately, the Blender Exporter is not supported anymore. So I decided to try to use the glTF 2.0 format. 
So, I exported the Luffy's hat in this format (see below the link to the model), and I tried to import it using the gltf loader demo included in JeelizFaceFilter. But I get a black hat (the shape is good, but not the texture). 
What I can't figure out is if the problem comes from my settings, or my Blender export ?

**To Reproduce**
1. Download the jeelizfacefilter-master repository > unzip it > cd to the jeeliz directory
2. Run http-server (or equivalent)
3. Go to the demos/threejs/gltf_fullScreen/ -> the helmet filter loads (but it seems )
4. Download the [Luffy's Hat exported from Blender](https://s3.eu-west-3.amazonaws.com/com.julianlecalvez/LuffysHat.zip)
5. Replace the path to the helmet with the one to the luffy's hat 
6. Refresh the webpage > The hat has no texture 

**Expected behavior**
I would expect the rendered Hat to be textured. When I upload 

**Screenshots**
Here is the result I get : 
<img width="1655" alt="Screen Shot 2019-10-14 at 13 05 29" src="https://user-images.githubusercontent.com/924826/66746873-596db800-ee83-11e9-9675-5975d94d2f6f.png">
Here is what I get when I upload the zip above in the [gltf viewer tool](https://gltf-viewer.donmccurdy.com/)
<img width="1663" alt="Screen Shot 2019-10-14 at 13 06 47" src="https://user-images.githubusercontent.com/924826/66746980-a5206180-ee83-11e9-9569-05f4a21a6e8d.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6 
 - Browser : Chrome 
 - Version : 77

**Comment by xavierjs** [comment]
I close this issue since it is more related to general help with THREE.js than this library.

**Comment by katiasmet** [comment]
@julianlecalvez  Were you able to solve this problem? I have the same problem. The texture is embedded in the file, so it should be loaded automatically.

**Comment by julianlecalvez** [comment]
For the luffy's hat, adding a light to the scene did the trick. 
But it didn't work with all my glTF files, and I couldn't understand why.

**Comment by xavierjs** [comment]
Sometimes textures are not power of two. Some GPUs / browsers requires that all textures should be power of two. It is not a problem to stretch them since UV are relative.

**Comment by Marwen-Bhj** [comment]
when I load any other .gltf file besides the original DamagedHelmet, by including its path, it doesn't display on the demo, @julianlecalvez luffys_hat , was the only imported .gltf file that got displayed, any clue or guidance please
