### ISSUE TITLE
Need to update the tutorials

### ISSUE THREAD

**Issue by raviranjan0631** [jeeliz/jeelizFaceFilter#134]
Hi, there are various issues with your tutorial as your tutorial is not explaining the same as written in the code for example. You guys have to update your tutorial too as we can't export 3d model from the blender too using JSON file

**Comment by xavierjs** [comment]
Hi,
We don't need you tell us what we have to do.
The tutorial target people who are already developers and who already have a basic knowledge in CS. It is easy to adapt to the latest changes.
We are currently working on other stuffs. If you submit the changes to add to the tutorial I can still apply them.

**Comment by dineshBD** [comment]
@raviranjan0631 You can use an older version of Blender to use export as Threejs JSON.
