### ISSUE TITLE
Having difficulty using JeelizThreejsHelper in ReactApp

### ISSUE THREAD

**Issue by dineshBD** [jeeliz/jeelizFaceFilter#137]
I am integrating the demo "football_makeup" in a react app. It requires JeelizThreejsHelper. After I use "import * as THREE from 'three' " , I get the error:-    "export 'JeelizHelper' (imported as 'THREE') was not found in 'three' ". What should I do?  In the file JeelizThreejsHelper.js, I am using "export default THREE" at the bottom. Please help thanks!

**Comment by AnastasiiaaaaM** [comment]
I solved it setting in webpack.config.js

`new webpack.ProvidePlugin({
        'THREE': 'three'
      }),`

**Comment by xavierjs** [comment]
If somebody want to submit a PR with a React (or Vue or Angular) boilerplate it would be accepted for sure :). Waiting this I will group the tickets relative to React integration and link them from the readme.

**Comment by dineshBD** [comment]
@AnastasiiaaaaM I am using a create-react app. I do not have webpack.config.js. How do I use your suggestion?

**Comment by dineshBD** [comment]
@AnastasiiaaaaM If its possible for you to publish your code for your React app, that'll be very helpful. thanks

**Comment by AnastasiiaaaaM** [comment]
@dineshBD I'll do it a bit later. 
For now, I ejected the webpack from react-create-app: https://stackoverflow.com/questions/48308936/what-does-this-react-scripts-eject-command-do

**Comment by xavierjs** [comment]
Hi,

I have added a section about using this lib with bundlers like Webpack:
https://github.com/jeeliz/jeelizFaceFilter#with-a-bundler

I wish it will help

**Comment by dineshBD** [comment]
Thanks @xavierjs @AnastasiiaaaaM I'll work on these suggestions.

**Comment by helsung** [comment]
is it possible to use jeeliz on an expo react-native project?

**Comment by xavierjs** [comment]
> is it possible to use jeeliz on an expo react-native project?

We don't handle react-native

**Comment by MUSTAQ1995** [comment]
how can i use these filters in my react app, can you please tell m, not getting the procedure.
