### ISSUE TITLE
Error JSON - Blender & ThreeJS - Unexpected token < in JSON at position 0 in React app

### ISSUE THREAD

**Issue by dineshBD** [jeeliz/jeelizFaceFilter#139]
I am unable to find a correct way to use the JSON file of the 3D model in react app. I get "Unexpected token < in JSON at position 0" if I use the function "loader.load" as used in threejs demos. [This ](https://stackoverflow.com/questions/49394040/json-blender-threejs-unexpected-token-in-json-at-position-0) states that the JSON file shoud be in public folder. If I shift the JSON file in public folder than I am getting error "cannot import files outside ./src folder". Can you suggest a correct way?

**Comment by xavierjs** [comment]
THREE.js should load this JSON file using Ajax. You need to check webpack config. When I am talking about a "public folder" tell before that content should be served through a static HTTP server. Webpack is not a standard static HTTP server.

You should take a look how THREE.js file loaders are made, and also how to inspect network traffic using the Network tab of your browser development tools.

**Comment by dineshBD** [comment]
I hosted the JSON file online and then passed it into the function. Thanks again you are always helpful :D
