### ISSUE TITLE
Using with webrtc

### ISSUE THREAD

**Issue by cwoo3511** [jeeliz/jeelizFaceFilter#141]
Hi,

First thank you this is a great code.
Can I apply this example to a video chat using webrtc?
Or can you give me some advice on making a video chat?

Please.

**Comment by xavierjs** [comment]
Hi,

You can use an external element ( see #50 )
Then doing a video chat using WebRTC is out of scope of this repository, that's why I am closing this issue.

**Comment by cwoo3511** [comment]
Thank you for your answer, but one more question.

I know it's possible to have a local video chat,
but I don't know any real time video chat using face filters between the two devices.
Is it possible?

Please I will not bother you anymore.

**Comment by cwoo3511** [comment]
Thank you for your answer, but one more question.

I know it's possible to have a local video chat,
but I don't know any real time video chat using face filters between the two devices.
Is it possible?

Please I will not bother you anymore.

**Comment by cwoo3511** [comment]
Thank you for your answer, but one more question.

I know that video chat is possible,
but I don't know if a video chat using the jeeliz face filter is possible.
Is it possible?

Please I will not bother you anymore.

**Comment by xavierjs** [comment]
it is possible if you add the face filter on client side.

**Comment by cwoo3511** [comment]
It's too hard for me. T.T
I don't know how to get media stream from face filter.
I need to use it in WebRTC P2P...

https://codelabs.developers.google.com/codelabs/webrtc-web/#4
