### ISSUE TITLE
How to make ES6 file work with React

### ISSUE THREAD

**Issue by dineshBD** [jeeliz/jeelizFaceFilter#142]
Hey Xavier, I am using jeelizFacePatched.js from [JeelizTest](https://github.com/ikebastuz/jeelizTest)  
 in my react app as I was getting so many errors if I import the ES6 version. I want to add multi-face detection but I cant do that with jeelizFacePatched.js as it missing the videoElement object in the init function which is required by JeelizHelper. What changes do I have to make in the ES6 file to make it work with React? Thanks Xavier!

**Comment by dineshBD** [comment]
issue #138 is very similar to this but instructions arent very clear :(

**Comment by xavierjs** [comment]
Hi,

You could ask to the guy who did jeelizTest.

If we did a lib which is framework agnostic, it is not to talk about react, angular or vue. 
Of course you are welcome to provide information to integrate the lib with main JS Framework, but personnaly I don't want to provide support for JS libraries of Facebook, Google or Alibaba. We already have to support Apple products and their lame implementation of standards (WebGL, WebRTC, ...).

I have added some information on the main doc of FaceFilter about integration with these frameworks: https://github.com/jeeliz/jeelizFaceFilter#with-javascript-frontend-frameworks
It is not complete, but it gives some help.

Best,
Xavier

**Comment by dineshBD** [comment]
I understand, I will have a look at it again. Thanks!

**Comment by xavierjs** [comment]
A NPM/React/Three-Fiber boilerplate has been added to the repository: https://github.com/jeeliz/jeelizFaceFilter/tree/master/reactThreeFiberDemo
