### ISSUE TITLE
Unable to clear filter history

### ISSUE THREAD

**Issue by dineshBD** [jeeliz/jeelizFaceFilter#143]
I am trying integrate multiple face filters in react (threeJS based), I am doing this by changing the source of the face filter (texture) and the settings for it (like scale and other stuff) on click by calling a function which updates the source and the setting values. It works once, ie when no filter is applied, and I click on the first filter to apply, but when I click on the next filter, the texture of the previous is not cleared and both the new one and the first one is diplayed. 

My question is how do I clear the settings of the previous one before I load the new filter? Thanks

**Comment by xavierjs** [comment]
Hi,

Each time you change the input texture, you need to call again `JEEFACEFILTERAPI.set_inputTexture(<WebGLTexture> glTexture, <integer> width, <integer> height)`
If you update `glTexture` and rerun detection it will keep the old glTexture unless you explicitely call this function again to take account of the texture change.

I hope it will help you to solve the problem

**Comment by dineshBD** [comment]
I fixed it by using "THREESCENE.remove(THREEFACEOBJ3D)" before loading new values. But thankyou so much for your prompt reply.
