### ISSUE TITLE
I have a question?

### ISSUE THREAD

**Issue by arcpuree** [jeeliz/jeelizFaceFilter#145]
I want to know the file structure in folder /jeelizFaceFilter/demos/threejs/VTO/models3D (face.json, glassesFrames.json, glassesFramesBranchesBent.json, glassesLenses.json) 

How do I create that file?

thank you.

**Comment by xavierjs** [comment]
Hi

They are exported from Blender using the old THREE.js Blender JSON exporter.
All is explained here: https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/threejs

But now it is better to use GLTF (which is a kind of standardized JSON). Look at tutorials/doc/example of THREE.js for more information. There is also a demo using a GLTF file (search for GLTF in this page: https://github.com/jeeliz/jeelizFaceFilter )

**Comment by arcpuree** [comment]
[
![Capture](https://user-images.githubusercontent.com/17014293/69150644-b0fae580-0b0b-11ea-91fc-4d7b5ba1ea24.PNG)
](url)

Why did the model of the glasses come to the front?

thank you.

**Comment by xavierjs** [comment]
Hi,

You need to render a transparent mesh with a head or cylinder shape to update the Z-buffer and to not draw the glasses right branch. This mesh is the occluder.

The VTO use-case is handled by this demo: https://jeeliz.com/demos/faceFilter/demos/threejs/VTO/
source code: https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/threejs/VTO

If you open the main script: https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/threejs/VTO/demo.js
We import the occluder here:
```
occluderURL: "models3D/face.json"
```
and we add it here:

```
threeStuffs.faceObject.add(r.occluder);
  r.occluder.rotation.set(0.3,0,0);
  r.occluder.position.set(0,0.1,-0.04);
  r.occluder.scale.multiplyScalar(0.0084);
```

This helper will be used to:
https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/threejs/VTO/JeelizThreeGlassesCreator.js

The occluder will be instantiated in the main THREE.js jeeliz helper:
https://github.com/jeeliz/jeelizFaceFilter/blob/master/helpers/JeelizThreejsHelper.js

The function `create_threejsOccluder` can be useful for you.

**Comment by arcpuree** [comment]
thank you, but now I use GLTF  as you suggest.
