### ISSUE TITLE
Is there a way to test a static image(img tag)? 

### ISSUE THREAD

**Issue by mchello1986** [jeeliz/jeelizFaceFilter#146]
Thank you very much for making a good library first.
I tested all the examples, but I only have an example using the video tag.
Is there a way to use images like png or jpeg? (using img tag or file data)

Regards.

**Comment by xavierjs** [comment]
Hi,
Yes, you have to transfert it to a texture first. 
The 2 first face replacements demos provided with this repository implement the trick.
In this one for example: https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/faceReplacement/image
