### ISSUE TITLE
VTO Example - Colors

### ISSUE THREAD

**Issue by john-stant** [jeeliz/jeelizFaceFilter#149]
Hi, 

Congratulations for your great projects. I have a question regarding VTO example in jeelizFaceFilter. In JeelizThreeGlassesCreator file we find the following code for lenses:

const mat=new THREE.MeshBasicMaterial({
            envMap: textureEquirec,
            opacity: 0.7,
            color: 0x2233aa,
            transparent: true
});
  
If I change the values of opacity, color & transparent everything works fine and the lenses are modified accordingly.

We also find the following code for frames:

//custom material with fading at the end of the branches
        const uniforms=Object.assign(THREE.ShaderLib.basic.uniforms,
            {
                envMap: {value: textureEquirec},
                color: {value: new THREE.Color(0xf0f0f0)},
                uBranchFading: {value: new THREE.Vector2(-90,60)} //first value: position (lower -> to the back), second: transition brutality
            });

Unlike lenses, if we change the value of color, we see no changes to the grey frame(0xf0f0f0). Is there something wrong or not?

Thank you.

**Comment by xavierjs** [comment]
Hi,

The frame material is a custom shader material initialized here: https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/threejs/VTO/JeelizThreeGlassesCreator.js

It seems it does not use the color uniform.

Best,
Xavier
