### ISSUE TITLE
Question: is it possible to use/extend this library to detect not only faces ?

### ISSUE THREAD

**Issue by melkishengue** [jeeliz/jeelizFaceFilter#151]
Hello, many thanks for this awesome library!!

I would like to know if it is possible to use/extend this library in order to not only detect faces, but also others body parts, like an arm or feet for example. What would be the way to go in case it is feasible ? thanks.

**Comment by xavierjs** [comment]
Hi,

It is not possible to do it by yourself since we don't release our deep learning engine used to train the neural network models.
We could do this @Jeeliz but it is not in our current roadmap.

Best

**Comment by melkishengue** [comment]
Okay thanks!
