### ISSUE TITLE
Blank screen on Chrome Android

### ISSUE THREAD

**Issue by georginio** [jeeliz/jeelizFaceFilter#152]
Hi! 

Thanks for the work!

I am trying to apply filter but only see blank screen instead of video. 
OS is Android 7. 

I see this logs at console

`[.WebGL-0x9c78ca00]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips` 

`[.WebGL-0x9c78ca00]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.`

Is there way to check if filter fell back on `webgl` except blank screen?

**Comment by xavierjs** [comment]
Hi,

I don't have enough information to proceed debugging. Please provide:

* the browser, the version of the browser, the operating system, the version of the operating system, the device model and the GPU if it is a desktop computer,
* a screenshot of webglreport.com - WebGL1 (about your WebGL1 implementation),
* a screenshot of webglreport.com - WebGL2 (about your WebGL2 implementation),
* the full log from the web console.

**Comment by xavierjs** [comment]
Hi @georginio 

I have committed some changes, including fixing some undefined behavior (like affecting uniforms to null or undefined). Can you try again on your device?

Thanx
