### ISSUE TITLE
Feature request: Could you add Typescript Types for JeelizFaceFilter and helpers please

### ISSUE THREAD

**Issue by ThorstenBux** [jeeliz/jeelizFaceFilter#155]
Would be awesome to have Typescript types,

some are already available here:

https://gist.github.com/il-m-yamagishi/fb063983158240d7e69399330df4427f

**Comment by xavierjs** [comment]
Hi @ThorstenBux 
I don't use Typescript but yeah, I am open to accept a PR to add typescript types.
Best,
Xavier
