### ISSUE TITLE
Demo masks not correctly positioned

### ISSUE THREAD

**Issue by oliverhausler** [jeeliz/jeelizFaceFilter#158]
Also see https://github.com/jeeliz/jeelizFaceFilter/issues/157#issuecomment-584301582

# anonymous

- [ ] Mask much too small,
- [ ] becoming even smaller and displaced when looking sidewise.

![image](https://user-images.githubusercontent.com/8090341/74206418-b6228900-4c51-11ea-98e3-08e575afc7e1.png)
https://jeeliz.com/demos/faceFilter/demos/threejs/anonymous/

# tiger

- [ ] Eyes are too high. [The eyes don't match with the eyes of the tiger. If this is on purpose, fine, but it looks a bit strange to have two pairs of eyes.]

![image](https://user-images.githubusercontent.com/8090341/74206340-604de100-4c51-11ea-967e-a99d8d4c8fba.png)
https://jeeliz.com/demos/faceFilter/demos/threejs/tiger/

**Comment by xavierjs** [comment]
Hi,

Thank you for your feedback.
For the anonymous demo, yes, there was a deprecated chunk of code displacing the pivot point. I have pushed a fix.
For the tiger demo, the eyes are displaced and deformed. This demo is very weird, I still hesitate to remove it from the repository.

Best,
Xavier

**Comment by oliverhausler** [comment]
Yes, the tiger demo is quite neat, otherwise. I wouldn't discard it. Thanks for fixing anonymous.
Oliver
