### ISSUE TITLE
Is there any way to swap face with video format ?

### ISSUE THREAD

**Issue by UihyunKim** [jeeliz/jeelizFaceFilter#159]
Hello, 

Thanks for the incredible working !

I'm finding a way to swap face with video format. 
Is it possible with its library? if yes, do you have an example for that? 

I've read similar issues here but it seems it's the first case..

Thanks, have a nice day :)

**Comment by xavierjs** [comment]
Hi,

You mean replacing the face in the camera video with a face cropped from a video file ?

**Comment by UihyunKim** [comment]
Yes exactly. 

Such as GIF example(https://jeeliz.com/demos/faceFilter/demos/faceReplacement/gif/),
I want to replace to video format(such as mp4) instead of gif. 

I tried embed mp4 with this option;
videoSettings: {
      videoElement: VIDEOELEMENT
    },
following the example(https://jeeliz.com/demos/faceFilter/demos/canvas2D/fromVideoFile/)
but it seems webcam(for catch my face) does not turned on.

**Comment by xavierjs** [comment]
It is doable but as mentionned in the issue submission part ( https://github.com/jeeliz/jeelizFaceFilter/issues/new ), this is not a help forum.

You need to manage the input texture and update it using WebGL api.
Like in the face replacement demo.
Using `JEEFACEFILTERAPI.set_inputTexture` and `JEEFACEFILTERAPI.reset_inputTexture`

Best,
Xavier
