### ISSUE TITLE
FaceCut Helper documentation

### ISSUE THREAD

**Issue by nathancrowd** [jeeliz/jeelizFaceFilter#160]
Could there be some documentation on how to use the FaceCut helper? It's not very intuitive to implement and I cannot find any information or demos using it in the form it is provided.

**Comment by xavierjs** [comment]
Hi,
Not so much. If you mean the face replacement demos, I wrote some stuffs here: https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/faceReplacement/gif
I hope it can help.
