### ISSUE TITLE
Helpers cannot be imported from es/commonjs modules

### ISSUE THREAD

**Issue by juliendargelos** [jeeliz/jeelizFaceFilter#161]
All helpers relies on global namespace, making them unreachable from es or commonjs imports:

https://github.com/jeeliz/jeelizFaceFilter/blob/308dca6c7d282c381acee3263241a446bd70b30f/helpers/Canvas2DDisplay.js#L15

https://github.com/jeeliz/jeelizFaceFilter/blob/308dca6c7d282c381acee3263241a446bd70b30f/helpers/HeadControls.js#L24

https://github.com/jeeliz/jeelizFaceFilter/blob/308dca6c7d282c381acee3263241a446bd70b30f/helpers/JeelizFaceCut.js#L15

https://github.com/jeeliz/jeelizFaceFilter/blob/308dca6c7d282c381acee3263241a446bd70b30f/helpers/JeelizResizer.js#L15

https://github.com/jeeliz/jeelizFaceFilter/blob/308dca6c7d282c381acee3263241a446bd70b30f/helpers/JeelizThreejsHelper.js#L6

https://github.com/jeeliz/jeelizFaceFilter/blob/308dca6c7d282c381acee3263241a446bd70b30f/helpers/addDragEventListener.js#L15

Helpers should be at least in umd format so they can be used seamlessly in any sort of bundling pipeline, and still be available from global namespace when needed.

For JeelizThreejsHelper.js, an `install` method taking `THREE` as argument should be exported so it doesn't directly manipulate the global namespace (where `THREE` might not be available neither).

Same for Canvas2DDisplay.js and `JEEFACEFILTERAPI`.

**Comment by xavierjs** [comment]
Feel free to submit a PR if you really think that things should be done this way.
