### ISSUE TITLE
Webcam unavailable error on iOS 13.4 error.

### ISSUE THREAD

**Issue by andrewdeutsch** [jeeliz/jeelizFaceFilter#162]
* A clear and concise description of what the bug is: what you expect and what happens

iOS 13.4 is generating web cam unavailable errors:

This is the entire error on a face tracking app (http://www.movable-ink-7158.com/p/rp/0b1bd72caf086cc9.png):
`[Error] WEBCAM_UNAVAILABLE
	(anonymous function) (bundle.min.js:2:84214)
	handleCameraError (vendor.js:1:17559)
	handleCameraError
	promiseReactionJob`

This is the entire error in a face replacement app (http://staging.movableink.com/p/rp/78810c3bd99aaf14.png):
`[Error] TypeError: undefined is not an object (evaluating 'this.errorMessage.element') — vendor.js:0
	handleCameraError (vendor.js:1:17559)
	handleCameraError
	promiseReactionJob`

A WebRTC getUserMedia demo works as expected:
https://webrtc.github.io/samples/src/content/getusermedia/gum/

* How to reproduce it (a code chunk or a link would be great),
Links above

* Some screenshots if applicable,
* Detailed information about your configuration, especially if you are facing a compatibility error with a specific device. Please read [this section of the README](https://github.com/jeeliz/jeelizFaceFilter#compatibility).
iPhone X running iOS 13.4 beta 2

**Comment by mnutt** [comment]
After a little bit more digging into this one, the `getUserMedia()` promise is returning successfully but where it's breaking seems to be jeeliz's `<video>` element; `currentTime` is always at `0`. Possibly `autoplay` no longer having an effect? Weirdly, if I manually advance `currentTime` to `0.1` I get a single video frame sent to jeeliz but no continuous video feed.

**Comment by xavierjs** [comment]
Hi,

This is really strange. I will test tomorrow, I don't have my Ipad with me today.
I guess they have changed again the WebRTC implementation. The main difference between the working example and Jeeliz lib is the video constraints.

Best,
Xavier

**Comment by xavierjs** [comment]
Hi @andrewdeutsch @mnutt 

I tested on iPad pro 10.5' with the latest ipadOS 13.4 beta and everything works fine.
I tested with Safari. I tested your 2 demos, the facefilter boilerplate, and https://jeeliz.com/sunglasses
Are you using Safari?
Have you tried to reboot the device?

Best,
Xavier

**Comment by andrewdeutsch** [comment]
Hi all,
It was a Beta 2 issue. They released Beta 3 yesterday and the issue's been resolved. 
Thanks for taking a look, @xavierjs.

**Comment by xavierjs** [comment]
Arghhhh it means that Apple is tinkering with WebRTC for next iOS versions... They should just keep it as is for web sake. I am pretty sure new workarounds will have to be implemented :-/ .
