### ISSUE TITLE
glb loading issue vto

### ISSUE THREAD

**Issue by ashishsiddharth** [jeeliz/jeelizFaceFilter#164]
Hi, What is wrong in here?? why isn't it working?

```
const threeGlasses = new THREE.Object3D();
const loader = new THREE.GLTFLoader();
   loader.load( 'models3D/glasses.glb', function (glassesFramesGeometry) {
		glassesFramesGeometry.computeVertexNormals();
		const glassesFramesMesh = new THREE.Mesh(glassesFramesGeometry);
		threeGlasses.add(glassesFramesMesh.scene)		
   });

  const occluderMesh = THREE.JeelizHelper.create_threejsOccluder(spec.occluderURL);
  
  return {
    glasses: threeGlasses,
    occluder: occluderMesh
  };
```

**Comment by xavierjs** [comment]
Please read the guidelines before submitting an issue. This is not a THREE.js help forum.

**Comment by ashishsiddharth** [comment]
Hi..! I have used stl file format to load different frames. But I wanted to load textures too. Hence i chose glb format. But computevertexnormal function is not working with gltf loader. Could you guys please guide how should i move ahead.
