### ISSUE TITLE
Faces added to a Three js scene not detected, is this possible? 

### ISSUE THREAD

**Issue by minenkod** [jeeliz/jeelizFaceFilter#166]
When adding a mesh of a face to a scene, it is not detected by the JeelizFaceFilter. For example It would be cool to faceswap my face in the webcam video with another face from a threejs canvas. They are technically both in the same canvas right? 

I found no examples doing anything like this, could this be done?

**Comment by xavierjs** [comment]
Yeah, it can be done.
