### ISSUE TITLE
threejs face recognition pipeline or face analysis

### ISSUE THREAD

**Issue by stefanache** [jeeliz/jeelizFaceFilter#167]
Hi,
Firstly, thanks for this great job!
Have you some samples in threejs_jeelizFaceFilter for
Face analysys or atleast Face-Recognition?
Something like step by step for :
face detect: rectangle and  face descriptors(landmarks/keypoints)
Face/head post estimation,
Feature extraction,
matching,
face registry
Thanks.

**Comment by xavierjs** [comment]
Hi,

Nop we don't provide that.
This library does not work as many other libraries, that's also why it is so fast.
I don't compute landmark position before computing the pose.
The neural network directly outputs pose parameters.

Best,
Xavier

**Comment by stefanache** [comment]
thanks a lot...
