### ISSUE TITLE
Problem with video FOV

### ISSUE THREAD

**Issue by soyrandom1** [jeeliz/jeelizFaceFilter#168]
Hello, i'm having an issue with the video FOV, i saw some posts talking about this but i couldn't find a solution.
The video i'm getting from the filter is too 'zoomed in', i tried tweaking it with JeelizResizer but i didn't see much difference between a super big resolution and a smaller one.
I basically want it to be less zoomed in but i can't achieve that

**Comment by xavierjs** [comment]
Please explain better your problem, I can do nothing for you with such a dumb bug report.

**Comment by soyrandom1** [comment]
Yes, i'm sorry about that. To be fair it's not a bug report, i think the documentation is not very clear about this.
Basically, my face looks too big, it's way too zoomed in, i want it to be more zoomed out, i know permormance wise is not the best thing to do, but i don't care
much about performance.

**Comment by xavierjs** [comment]
I think it is a problem with media constraints. You should test to ask video constraints matching your canvas size aspect ratio. Otherwise the video needs to be cropped and the perceived effect is a zoom in.
