### ISSUE TITLE
Simple demo using VueJS

### ISSUE THREAD

**Issue by tetreault** [jeeliz/jeelizFaceFilter#17]
I'm rebuilding the HeadCursor demo using head tracking to emulate mouse movement of a fake cursor i have on the page. I have code running, but the `STABI.xy` values never update. 

**Describe the solution you'd like**
See some method of this demo using something like Vue or React. 

**Describe alternatives you've considered**
I could always create this project the "old school" way not using a framework like Vue, but I really wanted to attempt recreating this using VueJS

**Additional context**
To see what I mean please run `git clone https://github.com/tetreault/face-filter-experiments` and then `cd face-filter-experiments` and `npm i` and then go to `localhost:3000/headmouse` and check out the console log for what I mean. 

The small isolated code snippet can be found inside `face-filter-experiments/pages/headmouse.vue`

**Comment by xavierjs** [comment]
Thank you for your interest for the lib, sorry I was not fast enough.
I would be glad to see the result of your work as soon as it is ready :)

**Comment by tetreault** [comment]
thanks for the reply @xavierjs! here's a [link](https://facefilter.party/headmouse) to the demo, nothing too special as I just wanted to recreate your demos using vuejs. i'll be building out cool things using jeeliz the more familiar I get with threejs/aframe/etc.

**Comment by xavierjs** [comment]
Hi @tetreault 

What's up about Vue.js integration and your demo?
I would be glad to add a link to your demo from the main README or a link to a github including a Vue.js integration.

Best,
Xavier

**Comment by xavierjs** [comment]
Edit: It is possible to get the video into an IOS webview with a hack (video is streamed to websockets).
Jeeliz Weboji ( https://github.com/jeeliz/jeelizWeboji ), which is similar to this library has been ported successfully in a native IOS app ( https://youtu.be/yx9uA1g6-rA ).

The implementation with Apache Cordova is here: https://github.com/jeeliz/jeelizWeboji/tree/master/demos/cordova
