### ISSUE TITLE
FaceFilter is freezing on Xiaomi Mi 9 Lite

### ISSUE THREAD

**Issue by lucas-carneiro** [jeeliz/jeelizFaceFilter#173]
First of all, thank you @xavierjs for this wonderful library! It was the best face detection library that my team found after some long research. Although we are having a great experience with it, we found a strange behavior while testing it with a Xiaomi Mi 9 Lite. We tried 3 different demos ([Babylon.js boilerplate](https://jeeliz.com/demos/faceFilter/demos/babylonjs/cube/), [Statue Of Liberty](https://jeeliz.com/demos/faceFilter/demos/threejs/multiLiberty/) and [CSS3D boilerplate](https://jeeliz.com/demos/faceFilter/demos/CSS3D/div/)), and all of them reproduced this bug below:

* **Expected behavior:** FaceFilter should not freeze because of any user movement.

* **How to reproduce:** We found the behavior above while randomly moving the user's head and device. The video below shows these movements and how FaceFilter freezes (0:23):
https://drive.google.com/file/d/1UQBPTv0PD_Rqd4DQlri7KuqS51D0w6j3/view

* **Additional bug info:** After FaceFilter freezes, refreshing the webpage does not solve the problem. The only solution that we found was to suspend the browser, go to another app, and return to the browser. The page automatically refreshes and FaceFilter starts working properly again.

* **Device info:**
  * **Browser:** Google Chrome 81.0.4044.138
  * **Operating System:** Android 10 QKQ1.190828.002 with MIUI Global 11.0.2
  * **Device Model:** [Mi 9Lite](https://www.gsmarena.com/xiaomi_mi_9_lite-9862.php)
  * **GPU:** Adreno 616

**Comment by xavierjs** [comment]
Hi Lucas,

What is the output of the JS console?
It looks a hardware/browser problem, and unfortunately I don't have a Xioami phone to test it...
You can try to set a slight animation delay between rendering loops by running:
```
JEEFACEFILTERAPI.set_animateDelay(2);
```
(Run it only once, after FaceFilter init, it will set a 2 ms delay between each rendering loop).
It will introduce an additional latency but may help the browser / GPU to not be too overwhelmed.

**Comment by lucas-carneiro** [comment]
> Hi Lucas,
> 
> What is the output of the JS console?
> It looks a hardware/browser problem, and unfortunately I don't have a Xioami phone to test it...
> You can try to set a slight animation delay between rendering loops by running:
> 
> ```
> JEEFACEFILTERAPI.set_animateDelay(2);
> ```
> 
> (Run it only once, after FaceFilter init, it will set a 2 ms delay between each rendering loop).
> It will introduce an additional latency but may help the browser / GPU to not be too overwhelmed.

@xavierjs Sorry, I forgot to say that there wasn't any error logs. The only logs that we got while testing it were face detected and face lost. We will test the delay and see if we have any results.

**Comment by xavierjs** [comment]
Arggg it looks a nasty browser / GPU driver / OS bug :(

**Comment by xavierjs** [comment]
Hi,

What's about the animateDelay? Does it help?

**Comment by lucas-carneiro** [comment]
Hello Xavier,

We tested it with 2 ms but the error still persisted. Then we increased it to 25, 50 and 100 ms and got the same results. In all tests we tried different gestures and movements with the camera (even standing still), but we couldn't find a way to easily reproduce the error, so we got different times for each test. Do you recommend any other solutions?

**Comment by xavierjs** [comment]
Hi Lucas,

Did you tested on several Xiaomi Mi 9 Lite or it is always the same device?

**Comment by lucas-carneiro** [comment]
Unfortunately we only have one Mi 9. We tried to reproduce the problem on other devices (including other Xiaomi devices), but we couldn't.

**Comment by xavierjs** [comment]
Maybe this one has a GPU a bit fucked.
