### ISSUE TITLE
Textures in glb model gets flipped

### ISSUE THREAD

**Issue by ashishsiddharth** [jeeliz/jeelizFaceFilter#175]
I have verified my glb model, it loads fine in any viewer. 
But when i load it using jeeliz face filter. Textures in my glb model gets flipped. 

What should i do? Here is my code, let me know if i am missing. Do i know need to flip canvas or some thing, i understand it is due to camera. texture gets reversed..??

> const loader = new THREE.GLTFLoader();
> loader.load( 'models3D/goggles.glb', function (glassesFramesGeometry) {
> 	   var model = glassesFramesGeometry.scene;
> 	   model.traverse ( ( o ) => {
> 			if ( o.isMesh ) {
> 				o.material.metalness = 1;
> 				o.material.roughness = 1;
> 			}
>             } );
> threeGlasses.add(model);
> });

**Comment by xavierjs** [comment]
This problem is related to THREE.js, not facefilter

**Comment by ashishsiddharth** [comment]
Hi, i have already mentioned, The model loads fine using threejs. Texture are okay. But when i load it using using face filter api, textures get reversed.

**Comment by xavierjs** [comment]
What version of THREE.js are you using? Did you tried with the latest one?

**Comment by ashishsiddharth** [comment]
it is latest version

**Comment by xavierjs** [comment]
Please provide a full example so that I can test (source code with the GLTF model).

**Comment by ashishsiddharth** [comment]
please find loader file in here
[loader.txt](https://github.com/jeeliz/jeelizFaceFilter/files/4664881/loader.txt)

and the api
[glb-jeeliz.txt](https://github.com/jeeliz/jeelizFaceFilter/files/4664889/glb-jeeliz.txt)

**Comment by ashishsiddharth** [comment]
Hi... ! I have included source code and glb model in here inside zip file... please have a look

**Comment by xavierjs** [comment]
Provide the full project otherwise I won't look.

**Comment by ashishsiddharth** [comment]
hi... !
I have included full source code...

[siddharth.zip](https://github.com/jeeliz/jeelizFaceFilter/files/4665160/siddharth.zip)

**Comment by xavierjs** [comment]
Hi,

Your canvas is flipped horizontally because of CSS.
The CSS rule: ` transform: rotateY(180deg);` is applied.

So your canvas is like a real mirror and the texture seems to be flipped horizontally.
It is more realistic.
If you try to read text through a mirror it will look inverted too.

Best,
Xavier

**Comment by ashishsiddharth** [comment]
Yeah... Thank u. I could get that it was due to mirror effect. I was unable to find this transformation line. Should have checked css file.

**Comment by ashishsiddharth** [comment]
Hi can this face filter api could be made more stable. I was thinking if instead of live camera, if I could import a video file. Will that do?? If so how should I import a pre recorded video..?

**Comment by xavierjs** [comment]
A demo is provided in this repo using a video file. Plz check the readme.
