### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by AkashNan** [jeeliz/jeelizFaceFilter#176]
Hi,

I am new in web AR technology. Been exploring this project for a while now. I have 2 feature suggestion or rather query on adding more demos.

In three.js section of this library, we have VTO demo. This demo uses .json for 3d models to load using geometry loader.  Use of .json for 3D model is a debate for us, so my queries are 

1. Can we see VTO demo using gltf models instead of .json ?
2. Is it possible to track individual parts of face using this library like nose, ear, lips? I did not see this ...is supported right now but is there any future plans on providing these features?

**Comment by xavierjs** [comment]
Hi,

1. Feel free to submit a PR for that,
2. Nop
