### ISSUE TITLE
VTO example 3D Model positioning

### ISSUE THREAD

**Issue by kunalluthade** [jeeliz/jeelizFaceFilter#177]
Hi,
I am exploring the JeelizFaceFilter Library where I was trying to augment jewelry on face(ears and neck)
I am facing difficulties while positioning it.
when I am turning my face the object is getting miss-placed.
Is there any way that I can fix the position?

I am attaching the code, I are modifing THREE.js VTO example.

```
// Left Earring
  const gltfLoader = new THREE.GLTFLoader();
  gltfLoader.load("./3D_assets/Left_Earring.glb", function (gltf) {
    gltf.scene.frustumCulled = false;
    gltf.scene.traverse(function (child) {
      if (child instanceof THREE.Mesh) {
        child.material = mat;
      }
    });
    threeStuffs.faceObject.add(gltf.scene);
    gltf.scene.position.set(0.77, -0.2, -0.3);
    gltf.scene.scale.set(8, 8, 8);
  });

  // Right Earring
  gltfLoader.load("./3D_assets/Right_Earring.glb", function (gltf) {
    gltf.scene.frustumCulled = false;
    gltf.scene.traverse(function (child) {
      if (child instanceof THREE.Mesh) {
        child.material = mat;
      }
    });
    threeStuffs.faceObject.add(gltf.scene);
    gltf.scene.position.set(-0.71, -0.2, -0.3);
    gltf.scene.scale.set(8, 8, 8);
  });

  // Necklace
  gltfLoader.load("./3D_assets/Necklace.glb", function (gltf) {
    gltf.scene.frustumCulled = false;
    gltf.scene.traverse(function (child) {
      if (child instanceof THREE.Mesh) {
        child.material = mat;
      }
    });
    threeStuffs.faceObject.add(gltf.scene);
    gltf.scene.position.set(0, -0.8, -0.5);
    gltf.scene.scale.set(5, 5, 5);
  });
```

Please find the attached snapshots:

![Front](https://user-images.githubusercontent.com/25146502/82549227-3a05de80-9b7a-11ea-8fb9-fad575a9334f.png)
![Left Ear](https://user-images.githubusercontent.com/25146502/82549230-3bcfa200-9b7a-11ea-99c6-3021d1d5de4e.png)
![Right Ear](https://user-images.githubusercontent.com/25146502/82549232-3bcfa200-9b7a-11ea-97f7-1958ee9e06d0.png)

Thanks in advance!

**Comment by xavierjs** [comment]
you need to disable the rotation part of the pose matrix of the necklace.
