### ISSUE TITLE
object is not defined

### ISSUE THREAD

**Issue by arist0tl3** [jeeliz/jeelizFaceFilter#178]
I'm guessing this bug will be present in any demo/project loading the jeelizFaceFilter.js file, but here is an example: https://jeeliz.com/demos/faceFilter/demos/threejs/daft_punk/

The experience fails to load with the following error:

`Uncaught ReferenceError: object is not defined`

Looks like just an issue of capitalization.

There are a few instances of the lowercased `object.assign` in the main js files:

https://github.com/jeeliz/jeelizFaceFilter/blob/master/dist/jeelizFaceFilter.js#L146
https://github.com/jeeliz/jeelizFaceFilter/blob/master/dist/jeelizFaceFilterES6.js#L150

Would be happy to open a pr, but it doesn't look like you expose the src here, so probably not worth opening against `/dist`.

**Comment by xavierjs** [comment]
Hi,
I have fixed the bug, thank you for your report. It should work now :)

**Comment by xavierjs** [comment]
BTW the daft punk demo is deprecated, like all demos whose source code is not included in this repository. There are some important bug about positioning. I have removed it from the demos list.
