### ISSUE TITLE
Blender plugin is removed

### ISSUE THREAD

**Issue by Rutulpatel7077** [jeeliz/jeelizFaceFilter#18]
https://github.com/mrdoob/three.js/tree/dev/utils/exporters/blender

Should we update our tutorials?

**Comment by xavierjs** [comment]
Hi,

Thanx for the update. That's too bad, the Blender exporter worked very well, I never had problem with it and the options were very useful and well chosen... I may add it in this repo.

**Comment by Rutulpatel7077** [comment]
@xavierjs  Thanks! man... I love your work
