### ISSUE TITLE
Does this estimate depth from image to enhance AR effects?

### ISSUE THREAD

**Issue by kafan1986** [jeeliz/jeelizFaceFilter#181]
1) Like AR Core and other framework that estimates depth from single image. Does this do the same? If yes, is it enabled by default?

2) Does the current version of this library has option of using depth data to improve the AR effect. If yes, then basically I have depth camera that gives real depth. Can I pass the depth map data somewhere in your framework to improve accuracy ar effects? https://github.com/intel/depth-camera-web-demo

**Comment by xavierjs** [comment]
We don't use depth camera and there is nothing planned to support it since depth camera video stream is not standardized in the web browser.

**Comment by xavierjs** [comment]
To be a bit more accurate, if this stuff was validated it would be great: https://www.w3.org/TR/mediacapture-depth/
Currently intel realsense camera depth stream is available in the web browser, but it is a bit a hack and it is not standardized (the 16 bits are mapped to red and green channels).

Then it would be possible to do background removal using jeeliz facefilter (we take the depth of the face and we remove stuffs farther away). But I won't work on it if there is no standard, and if mobile phones do not make the depth video stream available in the web browser.
