### ISSUE TITLE
jeelizFaceFilter.js err after camera turns on & model weights load

### ISSUE THREAD

**Issue by sharonzhou** [jeeliz/jeelizFaceFilter#183]
```
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at jeelizFaceFilter.js:32
    at XMLHttpRequest.e.onreadystatechange (jeelizFaceFilter.js:39)
```

I'm trying to load the face draw canvas2D demo but getting this error, at a cryptic place in the jeelizFaceFilter.js  script.  Not sure what function this is pointing to.

What works: the camera turns on (main() runs and according to the network, the weights file is fetched successfully), all css/styles load.

**Comment by sharonzhou** [comment]
Err on the line with `d = JSON.parse(d);` (pretty printed the minified script). Is this function for storing a byte (sb)? What's the greater context that it is for?

```
        function Sb(a) {
            if (I.ma)
                Db("string" === typeof I.ma ? JSON.parse(I.ma) : I.ma, a);
            else {
                var c = I.Ab;
                "JSON" !== c.toUpperCase().split(".").pop() && (c += H.save);
                Eb.get(c, function(d) {
                    d = JSON.parse(d);
                    Db(d, a)
                })
            }
        }
```

**Comment by sharonzhou** [comment]
I'm using node.js backend w/ parcel to build, vanilla js / html frontend (copied demo files to see if it could work)

**Comment by xavierjs** [comment]
The JSON NNC.json model seems to be loaded successfully but in fact it is not (check but I am sure it is not JON)
The problem does not come from the lib but from parcel or other shit.
