### ISSUE TITLE
Can run live demo links but not from downloaded zip

### ISSUE THREAD

**Issue by jjguest** [jeeliz/jeelizFaceFilter#188]
Hey, new to this so sorry if this is a waste of your time. As the title says, I can run the live demos from the links but not the demos from downloaded zip. This is with all browsers and all demos, the webcam flashes up for a second and then nothing, so maybe I'm missing something?

**Comment by xavierjs** [comment]
Use an HTTPs static server as explained in the README and learn the basics of web dev. I close the issue since it is too much a noob question.
