### ISSUE TITLE
The Great work  I ever found....! but one Question?

### ISSUE THREAD

**Issue by Rutulpatel7077** [jeeliz/jeelizFaceFilter#19]
**Is your feature request related to a problem? Please describe.**
How's our set position thing works?
Can you please explain how we can put sunglasses and hat on their exact place?

On the other hand,  can you please explain me how can I create this three values for sunglasses?

```
  hatMesh.scale.multiplyScalar(1.2);
  hatMesh.rotation.set(0, -40, 0);
  hatMesh.position.set(0.0, 0.6, 0.0);
```

**Describe the solution you'd like**
Should we create more tutorials?

**Additional context**
### I am interested in helping you guys let me know anything where I can help you with.

**Comment by Rutulpatel7077** [comment]
@xavierjs  Is that anything that, you can help me here?

**Comment by xavierjs** [comment]
Hi,

Just make hatMesh global :
window.globalHatMesh=hatMesh;

Then you can play with it in the JS console. For example:
globalHatMesh.scale.multiplyScalar(2); 
will make it 2 times bigger
You can then adjust the position, rotation and scale interactively.
As soon as you have the correct values, report them in your JS code

Thank you for your help proposal. We are open to pull requests, tutorials and if you have done a cool demo using this lib, we can add a link from the readme :)

Cheers,
Xavier

**Comment by Rutulpatel7077** [comment]
Thanks, for your reply.. @xavierjs 

I tried this.. works well

but I just want to ask you... I am trying to put Hair(model) on the Head.  But here I  am confused little bit because we are just rendering video behind the model right?

is there anyway I can put Hair on the top of my real hair ?

**Comment by xavierjs** [comment]
Hi,
Yes, we render the video behind the 3D model.
But since the video is rendered using a RawShaderMaterial, this is still possible to deform or tweak the rendering with GLSL in the fragment shader.
You will probably also need to render a transparent model of head in order to hide the back face of the hair 3D mesh. You can take a look at the statue of liberty face mask for example (https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/threejs/multiLiberty) there is also a tuto on WebGL Academy here : https://webglacademy.jeeliz.com/courses.php?courses=19_25_27_33_34#34

**Comment by tetreault** [comment]
+1 for this comment @xavierjs -- as a web dev wanting to learn and experiment with webgl this https://webglacademy.jeeliz.com/ link is something super handy. i'll be playing around with this more!

**Comment by Rutulpatel7077** [comment]
@xavierjs @tetreault   Thanks! guys

**Comment by Rutulpatel7077** [comment]
Hello, @xavierjs  any updates?

**Comment by xavierjs** [comment]
I have already pushed it here : https://github.com/jeeliz/jeelizFaceFilter/tree/master/libs/threejs/blenderExporter

It is thé exporter from three.js r83 I think. 
I use it with Blender 2.76 and it works fine.
