### ISSUE TITLE
GL_INCOMPATIBLE & WEBCAM_UNAVAILABLE issues coming up in couple of mobiles for my application but the demo works fine

### ISSUE THREAD

**Issue by Pritha-Roy** [jeeliz/jeelizFaceFilter#192]
Hi there!! First of all, Thank you so much for this wonderful library with so many useful features. I've integrated it in my Angular 10 project and it's working absolutely fine for most of the cases. But, I'm getting issues for couple of mobile devices I've tested on and I wonder why. 

Before I begin with the issue, my application is a 2-step Proof of Identity verification process where user is requested to take an image of the POI document and once done, user facing camera opens up and with the help of JeelizFaceFilter, system tries to track a face in the video feed. Once tracked, an image is taken automatically then user is requested to turn head towards right or left and once that activity tracked, again an image is taken and the process completes.

For most of the mobile devices it works fine. But, **for OnePlus 1 (Android 6, Chrome  86.0.4240.75)** it's not working and **throwing error "GL_INCOMPATIBLE"**. The device has no WebGL2 and here's extentions available for WebGL. 

![WhatsApp Image 2020-10-15 at 15 39 08](https://user-images.githubusercontent.com/51435737/96161880-7a089c00-0f35-11eb-8a68-2dc3a6cf552d.jpeg)

Curious is, the demo of jeeliz threejs/cube works fine on the device but through application, it always throws error as 'GL_INCOMPATIBLE' do you have any idea why this could happen?

For Samsung Galaxy S10  (Android 9, Chrome  85) it always shows "WEBCAM_UNAVAILABLE" even after user refreshes the page quite a few times. For this device also, the demo of jeeliz threejs/cube works fine.

I'm having no clue why these issues are keep popping up. Any suggestion would be great help. I've already checked all the related closed issues but nothing helped.

**Comment by xavierjs** [comment]
If the demo of threejs/cube works fine, it is not a problem with this library but an integration error.
Maybe the dimensions of your canvas are null or the video is not ready to play or there is something wrong with the canvas (a context already created, ...). Unfortunately, I don't use Angular.

**Comment by Pritha-Roy** [comment]
Thanks @xavierjs for your feedback. I also suspect so, but the apllication runs smooth on most of the mobiles I've tested(iphone 5,6, Realme 3pro, Redmi note 5, Samsung A31). If the canvas had any issue, it would occur for all devices I've tested with.

**Comment by xavierjs** [comment]
Can you share your code so that I can see
