### ISSUE TITLE
Rear cam used in Microsoft Surface

### ISSUE THREAD

**Issue by hunterpp** [jeeliz/jeelizFaceFilter#193]
On my microsoft surface all the demos switch to rear cam for some non-deterministic amount of time, then unexplainably switch back to user cam.

Yes, I have facingMode: “user” set

It is isolated to jeeliz because i went to https://webcamtests.com/

and it always showed front cam.

**Comment by xavierjs** [comment]
Hi @hunterpp 

Can you give me the full log of: https://jeeliz.com/demos/tests/2020-10-19/demos/threejs/cube/

Thanks, 
Xavier

**Comment by hunterpp** [comment]
[jeeliz.com-1603248349621.log](https://github.com/jeeliz/jeelizFaceFilter/files/5412966/jeeliz.com-1603248349621.log)
Yes, rear cam was active. Thank you

**Comment by xavierjs** [comment]
Hi @hunterpp 
Thank you for this log.
The video is accessed using these constraints:
```
{"facingMode":{"ideal":"user"},"width":{"min":480,"max":1280,"ideal":800},"height":{"min":480,"max":1280,"ideal":600}}
```
So it seems this is an error with MediaStream API implementation.
Maybe the size constraint is prioritized compared to the facingMode constraint.

Can you init facefilterAPI (not the helper) with different videoSettings (see https://github.com/jeeliz/jeelizFaceFilter#optionnal-init-arguments):
```
videoSettings: {
  'facingMode': 'user',
  'idealWidth': 1280,  //ideal video width in pixels
  'idealHeight': 720, //ideal video height in pixels
  'minWidth': 480,    //min video width in pixels
  'maxWidth': 1920,   //max video width in pixels
  'minHeight': 480,   //min video height in pixels
  'maxHeight': 1920,  

```

**Comment by xavierjs** [comment]
Hi @hunterpp 

Can you test the latest version I pushed on this github repository (the NPM package and the demos hosted on jeeliz.com have NOT been updated)? I have added a fix proposal where I try to access to the camera with `facingMode: {exact:  "user"` and if it does not succeed it fallbacks to `facingMode: {ideal:  "user"`

Thank you very much

**Comment by hunterpp** [comment]
Yes. I will test against old code side by side. Will take a few days

**Comment by xavierjs** [comment]
I have just updated the jeeliz.com hosted demos too, you can test here: https://jeeliz.com/demos/faceFilter/demos/threejs/cube2cv/
(please open in private navigation to avoid any browser caching problem).

**Comment by hunterpp** [comment]
tested in incognito....still displaying rear cam

**Comment by VGFP** [comment]
Hi, I have the same issiue. I belive it is chrome (new edge) problem (webex also saw only rear camera). Try using mozilla firefox it should allow to use front camera (it works for me).

**Comment by xavierjs** [comment]
It sounds like they want to imitate Apple regarding crappy MediaConstraints implementation...

**Comment by VGFP** [comment]
In Edge 87.0.664.55 and in Chrome 89.0.4343.0  you can now fix this go to: chrome://settings/content/camera or edge://settings/content/camera and change the camera (it works for me).
