### ISSUE TITLE
Unable to import JEEFACEFILTERAPIGEN from npm module

### ISSUE THREAD

**Issue by dyon048** [jeeliz/jeelizFaceFilter#195]
I was trying to import JEEFACEFILTERAPIGEN from npm module to create multiple videos on a page. I can't do it since  JEEFACEFILTERAPIGEN is not exported from jeelizFaceFilter.module.js. 

import { 
  JEEFACEFILTERAPI,
  NN_DEFAULT,
  NN_4EXPR,
  NN_LIGHT
} from 'facefilter';

I need to import JEEFACEFILTERAPIGEN, can I do that? 

Thanks for your help.

**Comment by xavierjs** [comment]
You need to detect faces on multiple videos simultaneously?

**Comment by dyon048** [comment]
> You need to detect faces on multiple videos simultaneously?

Yes. I need to detect faces from videos that come from the same camera and add different objects to each face.

**Comment by xavierjs** [comment]
If you want to detect multiple faces on the same video you don't need JEEFACEFILTERAPIGEN, JEEFACEFILTERAPI handles multi faces detection.

**Comment by dyon048** [comment]
> If you want to detect multiple faces on the same video you don't need JEEFACEFILTERAPIGEN, JEEFACEFILTERAPI handles multi faces detection.

I mean, I want to detect face from multiple videos. Those videos come from the same camera.
Like in here [](https://jeeliz.com/demos/faceFilter/demos/canvas2D/multipleTrackers/), but both videos come from the same camera.

**Comment by xavierjs** [comment]
Hi,

I have replaced `JEEFACEFILTERAPIGEN` global variable by the `create_new()` method (see https://github.com/jeeliz/jeelizFaceFilter#multiple-videos) so that it is possible to use it with the ES6 version.

**Comment by dyon048** [comment]
> Hi,
> 
> I have replaced `JEEFACEFILTERAPIGEN` global variable by the `create_new()` method (see https://github.com/jeeliz/jeelizFaceFilter#multiple-videos) so that it is possible to use it with the ES6 version.

Awesome! Thanks a lot for your great work. I will try it.
