### ISSUE TITLE
3d not shown

### ISSUE THREAD

**Issue by AjiNugroho** [jeeliz/jeelizFaceFilter#196]
dear Jeeliz company

i have tried to download the source fron this github,
then i run python file "httpsServer.py", and the an error come up , it said " SSLError EE_KEY_TOO_SMALL
then i tried to create self sign ssl certificate, and then the error solved

i run the server , open the browser then go to "htpps://localhost:4443" then select demo, then select three js demo, then select a demo then the browser just coming with camera and no filters at all, 
it just camera on the browser and nothing happen.

do i miss some steps ?

**Comment by xavierjs** [comment]
Do a real bug report (see https://github.com/jeeliz/jeelizFaceFilter#compatibility)
