### ISSUE TITLE
culling mask texture flip

### ISSUE THREAD

**Issue by aszymura** [jeeliz/jeelizFaceFilter#197]
Hello, we've got an issue with the occluder mask texture for almost all the demos :  it's flipped upside down for "rupy_helmet", "face_deform", "halloween_spider" and luffy_hat_part_2". We'have tested on 2 computers (windows ; latest Chrome and Firefox) and 2 mobile phones (Android ; One Plus and Xiaomi Redmi 8 Pro ; Chrome on both).

![image](https://user-images.githubusercontent.com/61796632/99382424-d4966e80-28cc-11eb-98e3-985951e24534.png)

Do you have an idea how it's possible ? 
We are pretty sure it's new because we find nothing about it in the Git issues.

Thank you.

**Comment by xavierjs** [comment]
Good catch bro! I was not applying the videoTransformMatrix which also flips the video.
Please re-open the issue if the bug is still here.
Online demos will be updated in 10 minutes

**Comment by aszymura** [comment]
Thanks a lot !
