### ISSUE TITLE
Camera's video not showing on iPhones, IPads and Chrome's Iphone/iPad simulator

### ISSUE THREAD

**Issue by yannklein** [jeeliz/jeelizFaceFilter#198]
When watched from an iPhone (tested with iPhone X, iOs 14.2), IPad (Pro 9.7inch, iOs 13.7) and Chrome's Iphone/iPad screen simulator (no problem on Surface, Samsung,... simulators), the `<canvas>` appears empty, no video is showing.
Here is a screenshot of the problem with the [AR raccoon Jeeliz demo](https://jeeliz.com/demos/weboji/demos/threejs/raccoon/):
![image](https://user-images.githubusercontent.com/26819547/99904053-ea13fa00-2d0b-11eb-9d3a-db12906a775c.png)
![image](https://user-images.githubusercontent.com/26819547/99904218-e765d480-2d0c-11eb-9219-4344cf60160a.png)

It looks like it's a `navigator` object problem. I though of quick-fixing the bug by editing `JeeelizFaceTransfer.js` this way:
#### Before
```
var a=navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/);
```
#### After
```
var a=navigator.appVersion.match(/OS X (\d+)_(\d+)_?(\d+)?/);
```

But it didn't work out (showing a GoPro WebCam screen instead). Still investigating...

**Comment by yannklein** [comment]
Note that it was working great until recently. I realized the problem last week on [a code](https://github.com/yannklein/lewagon-glasses), previously working well, that I haven't touched in 5 months. 
I believe an update of Apple devices messed up with Jeeliz code.

For the Racoon, the issue appears on `jeelizFaceTransfer.js`, for my code it appears on `jeelizFaceFilter.js` at the same `.match` stage.

**Comment by xavierjs** [comment]
Hi,

Thank you for your detailed bug report and fix proposals.
Indeed, there is an error, the navigator version should not be parsed like that since this parsing is for Safari and you are using Chrome.
But you will still get a WEBCAM_UNAVAILABLE error (caught by `callbackReady` callback function) since camera access is not allowed on Safari Webview, and Chrome for IOS is using a Safari Webview for web content rendering.

Related to #95 
Related to #129

**Comment by yannklein** [comment]
Hi @xavierjs 
Thanks a lot for your answer and the commited fix.
There is indeed a problem with Chrome's iPhone/iPad simulator, but the biggest problem, I think, is that the error message I reported occurs as well on Safari browser on iPhones and iPads (real devices).

**Comment by yannklein** [comment]
So, I figured out that my [Chrome + iPhone Simulator] and my [real iPhone + Safari] issues are two different issues!
I'll create another issue ticket for the [real iPhone + Safari] one. Feel free to close that one if you're managing the [Chrome + iPhone Simulator] topic in another issue ticket.

**Comment by xavierjs** [comment]
Hi @yannklein ,

It is great that it works now on Iphone + Safari (I fixed a major bug during the solving of issue #126 ). I regularly test the boilerplate on Iphone11 + latest IOS and Ipad pro + latest IOS in the beta channel. But there are often bad surprises with IOS updates.

I close this issue, feel free to re-open it if the problem occurs again.

**Comment by xavierjs** [comment]
**BREAKING NEWS**: Camera access is enabled on IOS14.3 which is released this Monday ( December 14th ). So FaceFilter will work on Chrome, Firefox, Opera for IOS, and into `WKWebviews` embedded in native apps.
