### ISSUE TITLE
Multiple face detection with high probability when a single face is present

### ISSUE THREAD

**Issue by DamascenoRafael** [jeeliz/jeelizFaceFilter#199]
First of all, thank you for this library and your commitment to making such an interesting resource available in such a simple way.

I am using multiple face (set to a maximum of 2) to try to ensure the presence of a single face. But sometimes when only one face is present, the probability of face detection for 1 and 2 appears with very high values (even when adopting a threshold of 0.9).

I noticed this behavior in my application (using version 2.0.5 via npm) and that can also be seen in the [multiCubes example](https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/threejs/multiCubes/main.js).

This behavior usually happens with the face in some positions or after some time moving the head. There is often a large overlap between the detection rectangles, but not always.

Is this behavior expected or is there a method to mitigate the problem? I tried a few different settings, but I was unsuccessful.

![IMG_4176-f](https://user-images.githubusercontent.com/9842644/100276579-89213780-2f40-11eb-88c2-366c0dfb1140.gif)

**Comment by xavierjs** [comment]
Hi,

I have worked to improve multi face detection and fixed a major bug.
Can you retry and tell me if it is better now?

Thanx
