### ISSUE TITLE
Demos not working on ThreeJS v120

### ISSUE THREAD

**Issue by spacorum** [jeeliz/jeelizFaceFilter#206]
First of all, I understand this is an specific ThreeJS issue, but I don´t have still enough information to ask for help on its own board, so please let me explain this here briefly.

The demos (I´m specifically trying with the Glasses VTO one) work well with the embedded ThreeJS version, which is v112. But if you try to use a newer version as v120, it throws an error hard to identify. I´m not even sure if it has something to be with GLSL shaders or maybe a call to an old geometry property. This is the error:

![jeeliz](https://user-images.githubusercontent.com/6510193/102791167-e5903f00-43a6-11eb-8f28-f45bd3618131.PNG)

By the way, the demo loads somehow, with limitations. You cannot see the camera image (just a white background) although the 3D glasses model is visible, but without any shader reflection. It follows the head movement correctly, anyway:

![jeeliz2](https://user-images.githubusercontent.com/6510193/102791331-27b98080-43a7-11eb-9a45-b3d8d4690fe3.PNG)

Could any advanced ThreeJS user have any clue about what is going on here? I really need the last version for compatibility purposses, so I would like to understand the issue and try to fix it. Sorry for posting this if it totally doesn´t belong here, thanks for your understanding.

**Comment by xavierjs** [comment]
Hi,

I close this issue since this is not a THREE.js help forum.
If you need support I can provide it (I charge for that). Please ask at contact__at__jeeliz.com

**Comment by spacorum** [comment]
I´ve just noticed current Jeeliz works perfectly up to THREE.js v117, but no more. My guess is that the error was related to WebGL2, which became the default in v118. Some other scripts don´t go well with WebGL2 too, so I think I´m going to step back for a while, until I understand WebGL2 better (too much changes to apply all of a sudden). I will use v117 for the moment.

Anyway, thanks for your offering, Xavier. Your work is amazing!

**Comment by xavierjs** [comment]
Oh I see what you mean. The glasses VTO demo, like most of current THREE.js demos, use only 1 canvas, for both computations with FaceFilter and THREE.js rendering.

This approach is deprecated. It is better to use 2 canvas to avoid GL state issues especially with the latest versions of THREE.js.
This is about 1 vs 2 canvases: https://github.com/jeeliz/jeelizFaceFilter#1-or-2-canvas
The current THREE.js uses 2 canvases: https://jeeliz.com/demos/faceFilter/demos/threejs/cube2cv/ and code here: 
https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/threejs/cube2cv

You just need to overlay the 2 canvases with CSS, use the canvas of the top for THREE.js rendering and the canvas of the back for computations & displaying video (like the boilerplate).

**Comment by spacorum** [comment]
Thank you so much for that links and samples. 
I finally was able to make it work using two canvas, as you suggested.
