### ISSUE TITLE
Video is rendering upside down.

### ISSUE THREAD

**Issue by sujoymondal87** [jeeliz/jeelizFaceFilter#208]
Hello Xavier, 
I've an issue with the new version of JEEFACEFILTERAPI initialization.

I'm getting the Video rendered Upside Down (My head is upside down not the helmet) and still the helmet seems to be following my face movements correctly

I'm expecting the video rotation at 0 degree, matching the helmet. But i'm getting 180 degree. Though I've tried with videoSettings.rotate : 180 in init method. It doesnot change anything in the rendered video.

I've also mention the full path of NN_DEFAULT.json in jeelizFaceFilter.js because NNC was not overriding the path.

I've tried to change isFlipY value to !1 instead of !0 in  jeelizFaceFilter.js line number 84, making the video renderring correct but then face detection seems not to detect "detectState" data properly and the object is not either following or placing itself on top of the head.

Thanks for your Help
Sujoy

**Comment by xavierjs** [comment]
Hi @sujoymondal87 

Which demo do you run with the bug in the current repository?
There were some breaking updates, so if you just changed the main script by the latest in your code this bug can happen.
