### ISSUE TITLE
The 'destroy' method fails if the device is not compatible

### ISSUE THREAD

**Issue by erickpires** [jeeliz/jeelizFaceFilter#223]
I'm trying to develop a robust way to either use FaceFilter in a compatible device or fallback in case the device is incompatible (to show the user a message saying that their device is incompatible).

By trial and error I found out that the best way to check for compatibility is to check if the device has access to `navigator.mediaDevices.getUserMedia` and then try to initialize FaceFilter and catch the error thrown when the device is incompatible (i.e. `"GL_INCOMPATIBLE"`).

If the aforementioned error is thrown, I try to call `destroy` to release any resources that may be allocated during the `init` call. Then I can display the user a message about the device compatibility.

What I noticed is that when I call `destroy` after receiving a `"GL_INCOMPATIBLE"` error, an error is thrown (apparently trying to access a property of a `null` value while trying to call `reset_GLState) as shown in the image bellow.

Just to check if the de-initialization worked despite the error, I called `init` one more time expecting to receive another `"GL_INCOMPATIBLE"` error, but instead I received an `"ALREADY_INITIALIZED"` error. My interpretation is that the de-initialization didn't happen completely.

I don't know if there's another way to fully `destroy` a FaceFilter instance that could not initialize successfully, but I think that throwing an error while trying to call `destroy` is  not the desired behavior.

I'm currently using the version 2.0.8 of FaceFilter from the NPM repository.

An image showing the error on the browser console:
![image](https://user-images.githubusercontent.com/6362864/109719014-cf60e500-7b86-11eb-8052-c2607ca5c079.png)

The minified location where the error occured:
![image (1)](https://user-images.githubusercontent.com/6362864/109719510-82c9d980-7b87-11eb-96bc-c3abb9861f3e.png)

**Comment by xavierjs** [comment]
Hi,

Thank you for this detailed bug report.
I have submitted a fix, I hope it will fix your issue.
I have also updated the NPM package to the 2.1.2 version (the same as the latest commit).

**Comment by erickpires** [comment]
Hello @xavierjs. Thank you for your quick response and for updating the NPM package.

I did some tests and the `destroy` method is working even on an incompatible device. Although an exception is still thrown and I had to catch it.

I'm closing the issue since the bug is now fixed.

One last thing. Is there some place where I can see a changelog? I was trying to find out what changed between versions 2.0.8 and 2.1.2 but didn't find a changelog here on Github.

Once again, thank you for your response and the amazing library I've created.

**Comment by xavierjs** [comment]
Hi @erickpires 

Thank you for your feedback.
There is currently no changeLog, it would be a good idea to add one.
I change the `VERSION` property of `JEEFACEFILTER` and sometimes I refresh the NPM package, using the same `VERSION ` value.
