### ISSUE TITLE
jeelizFaceFilter callback detectState.detected not working when camera streaming

### ISSUE THREAD

**Issue by theRussetPotato** [jeeliz/jeelizFaceFilter#227]
Probably related to issue #14 

**Description**
I'm trying to use a the face filter to map my face rotation to a circle going across the screen. All works well as expected until I try to use p5.js's `createCapture` to show the video on the canvas. Then the callback's `detectState.detected` value will only output very tiny values.

**How to replicate**
[Here's a sketch you can run online.](https://openprocessing.org/sketch/1146364)
Rotate your face to move the circle across the screen.
If you uncomment the `preload` function on top at lines 5-8, it will enable the camera and cause it to stop working.

**My config**
I'm on Windows 10, running the sketch above on Chrome.

**Comment by xavierjs** [comment]
This is a problem with p5.js, not with Jeeliz FaceFilter.
However, I can work on your code and on integration issues, but I charge for this.

**Comment by theRussetPotato** [comment]
Thanks for checking on this.
So to be clear is the problem with p5.js or my implementation?
