### ISSUE TITLE
ningún filtro de jeeliz funciona en mi safari en mi Mac

### ISSUE THREAD

**Issue by deylyn** [jeeliz/jeelizFaceFilter#228]
adjunto algunas fotos, no hay algun filtro que me funcione en mi safari, en Chrome me funcionan todos.
version de mi safari 13.1.2, Copyright © 2003-2020 Apple Inc
<img width="1280" alt="Captura de pantalla 2021-03-25 a la(s) 11 02 29 a  m" src="https://user-images.githubusercontent.com/24438895/112494804-ba2c4000-8d59-11eb-91b2-beec4175e41f.png">

<img width="1280" alt="Captura de pantalla 2021-03-25 a la(s) 11 01 05 a  m" src="https://user-images.githubusercontent.com/24438895/112494691-a2ed5280-8d59-11eb-9539-9e1451efa7e9.png">

**Comment by xavierjs** [comment]
ENglish plz
