### ISSUE TITLE
no jeeliz filter works on my safari on my Mac

### ISSUE THREAD

**Issue by deylyn** [jeeliz/jeelizFaceFilter#229]
safari version : 13.1.2, Copyright © 2003-2020 Apple Inc.
<img width="1280" alt="Captura de pantalla 2021-03-25 a la(s) 11 02 29 a  m" src="https://user-images.githubusercontent.com/24438895/112498660-23618280-8d5d-11eb-98d7-5cb55c3daf09.png">

<img width="1280" alt="Captura de pantalla 2021-03-25 a la(s) 11 01 05 a  m" src="https://user-images.githubusercontent.com/24438895/112498594-0fb61c00-8d5d-11eb-9691-ae2fabecb91a.png">

**Comment by xavierjs** [comment]
Hi,

Thank you for reporting this issue. Can you:

* retry in private browsing mode (I have updated the demos with the latest version of Jeeliz FaceFilter), Private mode is to avoid any browser cache issue,
* post the full log in the web browser console (I can only see the first lines in your screenshots),
* post the content of the textarea field of this debug script: https://jeeliz.com/demos/WebGLCoreLogger/index.html
* upgrade to safari 14 and retry

Thank you

**Comment by xavierjs** [comment]
Hi,

This bug could have the same origin as this one: https://github.com/jeeliz/jeelizFaceFilter/issues/232 which was fixed today.
Can you retry the demos (in private browsing mode to avoid any browser cache issue).
Thanx

**Comment by xavierjs** [comment]
I close this issue since I have no news about it. Feel free to re-open it if it still does not work.
