### ISSUE TITLE
Is it possible to reload jeelizFaceFilter and pass to it another video source for recognition? 

### ISSUE THREAD

**Issue by halidovz** [jeeliz/jeelizFaceFilter#23]
**Describe the solution you'd like**
Hi!
I want to be able to reload jeelizFaceFilter or pass another video source to it. Now it generates "already initialized" error when I try to start  jeelizFaceFilter more than once.
Is it possible?

**Comment by xavierjs** [comment]
Hi,

This is not possible to reload jeefitAPI. This lib use a lot of resources and to run several instances would decrease the performance too much. At the loading it will load the neural network model with AJAX and we want to avoid it occurs several times.

But it is possible to pass a custom video. You can check this demo where a <video> element is used : https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/canvas2D/fromVideoFile

or this one where we can change dynamically the input texture using set_inputTexture(<WebGLTexture> tex, <integer> width, <integer> height) and reset_inputTexture (described in the general readme)  : https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/faceReplacement

**Comment by halidovz** [comment]
@xavierjs thank you for reply. But I don't need to run several instances, I want to destroy the current running instance and restart it, but I guess anyway it's not possible.

Let me clarify one moment - I init api and set videoElement in videoSettings and the question was - can I change video element at run time?

**Comment by xavierjs** [comment]
This is definitely possible with set_inputTexture( tex, width, height) and reset_inputTexture methods, and this is what we do in the face replacement example.

But you cannot directly give a video element to these methods, you have to put your video into a webglTexture, to refresh it at each frame and to give this webGLtexture to  set_inputTexture method.

Then if you want to reset to the webcam video, you call reset_inputTexture()

**Comment by halidovz** [comment]
@xavierjs ok, I got it. Thank you!
