### ISSUE TITLE
Calling JEEFACEFILTERAPI.init after already called JEEFACEFILTERAPI.destroy causes multiple issues

### ISSUE THREAD

**Issue by albrand** [jeeliz/jeelizFaceFilter#230]
If you are submitting a bug report, please provide:

* A clear and concise description of what the bug is: what you expect and what happens,

When we call the init method of JEEFACEFILTERAPI after you already called the destroy method of JEEFACEFILTERAPI, it does not work as it was the first time you are calling it for some reason.

The context for this application is in that case, the API is isolated in a component which is a part of a parent component, that opens and closes it as a windowed experience, but using the same parent window instance. You can imagine it is a modal opening and closing.

* How to reproduce it (a code chunk or a link would be great),

This is how we used to load and destroy the API instance:
```
    useEffect(() => {
        JEEFACEFILTERAPI.init({
            canvas: canvas.current,
            NNC: NN_DEFAULT,
            maxFacesDetected: 1,
            followZRot: true,
            callbackReady,
            callbackTrack,
        });
        return async () => {
            await window.JEELIZFACEFILTER.destroy();
        };
    }, []);
```

It is using the [face.json](https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/threejs/glassesVTO/models3D/face.json) to generate the facial mask occluder, but it just works at the first time it loads up. When we re-execute the init method after destroying it, it doesn't come back. This is the shell we use to add it:
```
    const geometry = useLoader(
        THREE.BufferGeometryLoader,
        MASK
    );

    return (
        <mesh
            geometry={geometry}
            scale={[0.009, 0.009, 0.009]}
            rotation={[0.3, 0, 0]}
            position={[-0.01, 0.03 + 0.07, -0.25]}
        >
            <shaderMaterial
                args={[
                    {
                        vertexShader: THREE.ShaderLib.basic.vertexShader,
                        fragmentShader:
                            'precision lowp float;\n void main(void){\n gl_FragColor=vec4(1.,0.,0.,1.);\n }',
                        uniforms: THREE.ShaderLib.basic.uniforms,
                        colorWrite: false,
                    },
                ]}
            />
        </mesh>
    );
```

And also, we add some texture effects, but it only work at the first time. When we load it up at the second time, it crashes the application giving a fatal error. This is the code shell adding it:
```
    const textureEquirec = useLoader(THREE.TextureLoader, envMap);
    if (scene) {
        scene.traverse(child => {
            if (child.isMesh) {
                textureEquirec.mapping = THREE.EquirectangularReflectionMapping;
                textureEquirec.magFilter = THREE.LinearFilter;
                textureEquirec.minFilter = THREE.LinearMipMapLinearFilter;
                child.material.opacity = 0.7;
                child.material.transparent = true;
                child.material.envMap = textureEquirec;
            }
        });
        scene.scale.set(SCALE.x, SCALE.y, SCALE.z);
        return <primitive object={scene} position={[-0.0028, 0.27, -0.15]} />;
    }
```

* Some screenshots if applicable,

The error displaying when we rerun the FACEFILTERAPI component using the texture effects:
![image](https://user-images.githubusercontent.com/27248651/112788913-5001ec80-9032-11eb-95c4-481ae865ba96.png)

* Detailed information about your configuration, especially if you are facing a compatibility error with a specific device. Please read [this section of the README](https://github.com/jeeliz/jeelizFaceFilter#compatibility).

![image](https://user-images.githubusercontent.com/27248651/112788521-7410fe00-9031-11eb-9164-94e3887398ca.png)
![image](https://user-images.githubusercontent.com/27248651/112788554-84c17400-9031-11eb-9c16-05c6b94866cb.png)

**Comment by albrand** [comment]
I don't know if it is useful, but, another information is that I started deep diving into this and found that even when you call the destroy method, which inside has a getExtension('WEBGL_lose_context').loseContext(), when you re-open the component, it says the context wasn't lost:
![image](https://user-images.githubusercontent.com/27248651/112933578-8143f080-90f6-11eb-88ef-0dcf39379aa7.png)

**Comment by albrand** [comment]
All contexts are being managed outside, so it had to be controlled outside the library, discarding all Jeeliz libraries dependencies to do it.

**Comment by xavierjs** [comment]
Currently, the destroy() method should destroy all WebGL instances (textures, buffers, shaders, ...).
The context is not destroyed itself since I think it is weird to call an extension to destroy it.
There should be a simple method to unlink the context from the canvas and to destroy it. I don't know what is officially the best practice to destroy a WebGL context.
