### ISSUE TITLE
Demos not running with Firefox: "WebGL context was lost" Warning

### ISSUE THREAD

**Issue by domElement** [jeeliz/jeelizFaceFilter#232]
Hi, 

First of all great work with the library!

All demos online work great with Chrome but with Firefox 87.0 (64-bit) (using Ubuntu 20.04) the canvas element stays blank. This holds for all demos hosted on your website I tried so far (e.g. [this](https://jeeliz.com/demos/faceFilter/demos/threejs/cube/)), but also applies when cloning the repo and running the demos locally.

Opening the terminal I see the following: 
![error](https://user-images.githubusercontent.com/82111326/113903951-d0161800-97d1-11eb-8aeb-a01d5c145bfe.png)

I assume the problem is the `WebGL context was lost. jeelizFaceFilter.js:3:1667` warning, however, this remains a bit unclear to me as there is no obvious error message and it says `INFO: JEELIZFACEFILTER IS READY`.

On all compatibility websites ([webglreportv1](https://webglreport.com/?v=1), [webglreportv2](https://webglreport.com/?v=2), https://caniuse.com/) I get green lights.

Are you able to run the demos on your system with Firefox?

Edit: Same experience when using Firefox on my Android Smartphone (Chrome works well).

**Comment by xavierjs** [comment]
Hi,

Thank you for signaling this bug. I was able to reproduce it and I pushed a fix.
It should work now. Please empty your browser cache or try in private browsing mode.

**Comment by domElement** [comment]
Great, Firefox works now! Face detection /  keypoint detection seems to have gotten a bit more shaky though.

**Comment by xavierjs** [comment]
Hi @domElement 
I have pushed another fix to fix this bug this morning. I hope it will help
