### ISSUE TITLE
Can I use a pose estimation model

### ISSUE THREAD

**Issue by Marwen-Bhj** [jeeliz/jeelizFaceFilter#233]
following the same principle of face filters, I want to use this library for full body filters. So can I use a pose estimation model after conversion to .json in order to generate the feature keypoints and assign my 3D clothes to the detected landmarks ?

**Comment by xavierjs** [comment]
It is not possible since I fully use my own toolchain to create, train and use my neural networks model. It is not compatible with mainstream DL engines.
