### ISSUE TITLE
Compiler warnings: "export 'JEELIZFACEFILTER' was not found in 'facefilter'

### ISSUE THREAD

**Issue by carolinekabat** [jeeliz/jeelizFaceFilter#234]
Hey!

I just started to play around with this, thanks for the work with the library! I got stuck on the initial running of the demos:

**A clear and concise description of what the bug is: what you expect and what happens**:
I cloned the repository and tried to run `reactThreeFiberDemo`, but I got some compiler warnings (check screenshot) and wasn't able to run the demo correctly.

I guess it could maybe be something with the recent renaming of JEEFACEFILTERAPI to JEELIZFACEFILTER, seems like the npm module is not exporting correctly? If I change the import/export naming locally in index.js and run it again, the demo seems to work. Not sure if it's part of the issue, but it fixed the warnings for me and I was able to run the demo.

**How to reproduce it (a code chunk or a link would be great)**:
Clone the repo and follow the installation instructions, try to run the `reactThreeFiberDemo` demo.

**Some screenshots if applicable**:
Warnings after running `npm install` and `npm run start`:
<img width="1168" alt="Screenshot 2021-04-20 at 22 51 43" src="https://user-images.githubusercontent.com/5169531/115463007-9a3e4e00-a22b-11eb-96e6-bd053c1fd845.png">

Renaming locally in npm module:
<img width="920" alt="Screenshot 2021-04-20 at 23 23 01" src="https://user-images.githubusercontent.com/5169531/115465776-682eeb00-a22f-11eb-817c-2055b076f00e.png">

**Detailed information about your configuration**
Not related to the issue (I think)

**Comment by xavierjs** [comment]
Hi,

Thank you for this detailed bug report.
Indeed, it was because of the renaming from `JEEFACEFILTERAPI` to `JEELIZFACEFILTER`
I have updated the npm facefilter package to 2.1.7 which fixes the bug.
Or your side you can run:
```
git pull
npm upgrade facefilter
```

**Comment by reimertz** [comment]
Thanks for the work @xavierjs (and @carolinekabat  for filing).

It seems that it still some problems due to the index.js including import statements (not compiled to using require()...).

**Comment by xavierjs** [comment]
Hi,

I close this issue, feel free to re-open it if some exports lack in the NPM FaceFilter module.
