### ISSUE TITLE
Https not allowed this is my issue pls help me to put with domain

### ISSUE THREAD

**Issue by johnfelipe** [jeeliz/jeelizFaceFilter#240]
sudo apt-get install software-properties-common

	apt-get update
	apt-get install nginx

	sudo nano /etc/nginx/sites-available/default

i change this

	#server_name _;
	server_name demosena1.dap-udea.co;
	
And execute this:

	sudo nginx -t

	sudo systemctl reload nginx

	sudo apt install curl

	curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -

	sudo apt-get install -y nodejs

that one for install nodejs

#Ngnix setting for reverse proxy to work without port or with ssl

	cd /etc/nginx/sites-available
	touch ngnix.conf
	nano ngnix.conf

#add these lines
	server {
	listen demosena1.dap-udea.co:443;
	server_name demosena1.dap-udea.co;
	return 301 http://demosena1.dap-udea.co:3000; }

#(for nano ctrl-o then ctrl-m and then ctrl-x it will save and exit the file)

	cd /etc/ngnix/sites-enabled
	touch demosena1.dap-udea.co.conf
	nano demosena1.dap-udea.co.conf

#add this line

	server
	{
	 listen 443 ssl;
	 server_name demosena1.dap-udea.co www.demosena1.dap-udea.co;
	 location /
	 {
	 proxy_set_header Host $http_host;
	 proxy_set_header X-Forwarded-Host $host;
	 proxy_set_header X-Forwarded-Server $host;
	 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Graylog-Server-URL https://domain.com/api;
	 proxy_pass http://demosena1.dap-udea.co:3000;
	 # proxy_pass http://demosena1.dap-udea.co:3000;
	 }
	 ssl on;
	 ssl_certificate /etc/letsencrypt/live/demosena1.dap-udea.co/fullchain.pem;
	 ssl_certificate_key /etc/letsencrypt/live/demosena1.dap-udea.co/privkey.pem;
	 ssl_session_timeout 5m;
	 ssl_ciphers EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
	 ssl_protocols TLSv1.2;
	 ssl_prefer_server_ciphers on;
	 access_log /var/log/nginx/demosena1.dap-udea.co.access.log;
	 error_log /var/log/nginx/demosena1.dap-udea.co.error.log;
	}

	# http to https redirection
	server {
		listen 80;
		server_name demosena1.dap-udea.co www.demosena1.dap-udea.co;
		add_header Strict-Transport-Security max-age=2592000;
		rewrite ^ https://$server_name$request_uri? permanent;
	}

then this

	systemctl reload nginx

	apt -y install nginx

	sudo nano /etc/nginx/nginx.conf

change this 

	##
	http {

		##
		# Basic Settings
		##

To

	http {

		##
		# Basic Settings
		##
		client_max_body_size 100M;
	##

	sudo systemctl reload nginx
Or
	sudo service nginx restart

	add-apt-repository --yes ppa:certbot/certbot

	apt update

	apt -y install certbot

	certbot certonly --webroot -w /var/www/html -d demosena1.dap-udea.co

next i do this

	nano /etc/nginx/sites-available/demosena1

	##
	server {
		listen 443;
		server_name demosena1.dap-udea.co;
		ssl_certificate
		/etc/letsencrypt/live/demosena1.dap-udea.co/fullchain.pem;
		ssl_certificate_key
		/etc/letsencrypt/live/demosena1.dap-udea.co/privkey.pem;
		ssl on;
		ssl_session_cache builtin:1000 shared:SSL:10m;
		ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
		ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
		ssl_prefer_server_ciphers on;
		gzip on;
		gzip_http_version 1.1;
		gzip_vary on;
		gzip_comp_level 6;
		gzip_proxied any;
		gzip_types text/plain text/html text/css application/json application/javascript
		application/x-javascript text/javascript text/xml application/xml application/rss+xml
		application/atom+xml application/rdf+xml;
		gzip_buffers 16 8k;
		gzip_disable “MSIE [1-6].(?!.*SV1)”;
		access_log /var/log/nginx/demosena1.access.log;
		location / {
			proxy_pass
			http://localhost:3000;
			proxy_set_header host $host;
			proxy_http_version 1.1;
			proxy_set_header upgrade $http_upgrade;
			proxy_set_header connection "upgrade";
		}
	}
	##

then this

	ln -s /etc/nginx/sites-available/demosena1 /etc/nginx/sites-enabled/demosena1

	nginx -t

	sudo systemctl enable nginx
	

	systemctl restart nginx
	
in this path

root@glasses-ubuntu-s-8vcpu-16gb-nyc3-01:~# pwd
/root

	git clone https://github.com/jeeliz/jeelizFaceFilter.git
	cd jeelizFaceFilter/
	npm install

then this:

	npm run dev
	
but i need acces via 

https://demosena1.dap-udea.co/

![image](https://user-images.githubusercontent.com/428820/120040064-8d9bdb00-bfcb-11eb-90a2-b8882c2bb771.png)

**Comment by xavierjs** [comment]
I don't see what it has to do with Jeeliz FaceFilter
