### ISSUE TITLE
Tracking becomes disabled when web browser focus is lost

### ISSUE THREAD

**Issue by yagiziskirik** [jeeliz/jeelizFaceFilter#242]
Hello guys,

I have been trying to make an app to track faces for moving your head inside simulators. I have managed to make it work for X-Plane 11, works absolutely fine. But I have a problem, and I couldn't find a solution for it so far. It might be caused by something in the jeelizFaceFilter that I couldn't see, and I'm not very much experienced with the webcam interactions on Javascript.

When I change the active tab from the web face tracking tab to another or go to a different program, face tracking becomes disabled. I know that some of the websites have the functionality to keep your webcam open when you are not focused on it (for ex. Google Meet), but it doesn't seem to work with the jeelizFaceFilter webcam system.

I am using M1 MacBook Pro, and I tried to accomplish this with both Safari and Firefox. Also, I tried it with the 2019 MacBook Air but still no luck. It is crucial for me to keep face tracking after I click to somewhere else (in this case the X-Plane 11). I don't know if it is Mac related but I don't have a Windows computer nearby to test it. I know it is not a regular report that you get normally since users mostly use it to interact with it. This can be both a bug report or a feature request since I don't know which one it is right now. You created a perfect program by the way. I've deleted Snap Camera and Lens Studio after I discovered this. Thank you.

Edit: I recorded a video as well (I disabled the video output on purpose to hide my misery). The video cut short, but I will explain. Until I focus on X-Plane, as you can see it tracks my face perfectly fine. Even though it didn't show up in the GIF file after I click to X-Plane and Safari window disappears (clicking for the second time, end of the video), tracking stops immediately. And I confirmed it with JS console output using timestamps.

![vid](https://user-images.githubusercontent.com/33431578/120050680-6f16fd80-c026-11eb-8c06-209eb4ee3f08.gif)

**Comment by yagiziskirik** [comment]
Okay, I found the solution. It was already written on your documents, I couldn't see the argument which is responsible for this, it is my fault. You guys thought about that already.

I fixed the issue by adding `isKeepRunningOnWinFocusLost: true` parameter to `JEELIZFACEFILTER.init` function and it is working like a charm. Thank you for this amazing library again.

**Comment by xavierjs** [comment]
Related to #221
