### ISSUE TITLE
Title: WebGL Errors When Wrapping Jeeliz Project with Capacitor App (Android)

### ISSUE THREAD

**Issue by ccaleb** [jeeliz/jeelizFaceFilter#247]
# Platform
Android v7.0 and above

# Description
I have created a Jeeliz Face Filter project that works on both iOS and Android devices via their respective web browsers. However my client requires the project to be delivered as a native app via [CapacitorJS](https://capacitorjs.com/). I’ve successfully managed to create a native iOS version using Capacitor and it works as expected on iOS14.5 devices and above. However, whenever I run the Android version, the app fails to render any camera video to the screen and repeatedly reports the following series of WebGL errors on each frame update:

```
[ERROR:gles2_cmd_decoder.cc(18881)] [.RendererMainThread-0x400b3e800]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[ERROR:gles2_cmd_decoder.cc(8621)] [.RendererMainThread-0x400b3e800]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: Attachment textarget doesn't match texture target
[ERROR:gles2_cmd_decoder.cc(4993)] [.RendererMainThread-0x400b3e800]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawArrays: framebuffer incomplete
```

These errors appear in the Android Logcat window in Android Studio. It should be noted that I don’t see any specific errors being reported on the JavaScript console at this point. There’s nothing in the JavaScript console to indicate that Jeeliz has failed to initialise.

This issue happens with every Android device that I’ve tested with across various versions of Android. At the moment I’m testing with a Samsung Galaxy S6 running Android 7.0.

# Summary
* The exact same project runs within Chrome on my Samsung Galaxy S6
* The exact same project runs within Safari on all iOS devices that I’ve tested with (iPhone 7, iPhone 8, iPhone X, iPad)
* The exact same project also runs when running in a local web server on my development machine (Mac OSX)
* It’s only when being wrapped into a native app using Capacitor that it fails on Android
* Wrapping the same code into a native iOS app using Capacitor works
* I receive the above WebGL errors with my own project and all the Jeeliz demos that I’ve tested from the jeelizFaceFilter repo

# How to Reproduce
To keeps thing simple I’ve create a sample Capacitor project that wraps the jeelizFaceFiler/demos/canvas2D sample project into a native app. The project can be found [here](https://github.com/ccaleb/jeeliz-capacitor).

## Pull the source from the repo
Clone the source from [here](https://github.com/ccaleb/jeeliz-capacitor).

## Install packages
`> npm install`

## Test the project works on your local development computer’s browser
`> npm start`

This will start a secure web server session.
Open your web browser and enter 'localhost' into the address bar.

## Also test the project by running it on your Android device’s web browser
* Open Google Chrome on your Android device
* Obtain the IP address from your development computer
* Enter your IP address into the address bar of your device’s web browser

## Wrapping into a native app
Follow these steps to wrap your project into a native app using Capacitor:

### Add the Android Platform
`> npx cap add android`

### Open Android Studio
`> npx cap open android`

### Set Camera App Permissions
The following permissions need to be added to the app’s AndroidManifest.xml file.

Within Android Studio open the following file: app/manifests/AndroidManifest.xml

Add the following entries near the end of the file:

```
<uses-feature android:name="android.hardware.camera" android:required="false" />
<uses-feature android:name="android.hardware.camera.front" android:required="false" />
```

Save the file.

### Build Project
Connect an Android device to your computer.
From Android Studio, select the Run > Run App drop-down menu.

After a short time the app will build and deploy to your device.

# Expected Result
The app should show a live camera feed and also draw a yellow detection rectangle around your face.

# Actual Result
No live camera feed appears in the app.
When looking at Logcat within Android Studio, the following errors appear on each frame update:

```
[ERROR:gles2_cmd_decoder.cc(18881)] [.RendererMainThread-0x400b3e800]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[ERROR:gles2_cmd_decoder.cc(8621)] [.RendererMainThread-0x400b3e800]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: Attachment textarget doesn't match texture target
[ERROR:gles2_cmd_decoder.cc(4993)] [.RendererMainThread-0x400b3e800]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawArrays: framebuffer incomplete
```

# Additional Info
I’ve tried many of the Jeeliz FaceFilter demos with Capacitor and non of them work with the exception of demos/canvas2D/fromVideoFile. Of course this demo uses a video rather than working with the camera video feed but perhaps that sheds some light on what the issue could be.

# Device Configuration
This issue occurs on all Android devices I’ve tested with.
At this very moment I’m testing with a Samsung Galaxy S6 so I’ll provide its details here:

Samsung Galaxy S6
Android 7.0
Supports WebGL2

# Final Notes
Any information you can provide that might help resolve this issue would be really appreciated. Thanks for your time.

**Comment by xavierjs** [comment]
This project is not make to work as a native app.
I close the issue since it is not related to Jeeliz FaceFilter, but to the limitations of React Native.
