### ISSUE TITLE
Unable to update a shader uniform on real time.

### ISSUE THREAD

**Issue by jpupper** [jeeliz/jeelizFaceFilter#249]
So i´ve been following the matrix tutorial and i found it amazing. 
It taked me a little time before i was able to make it work (i think the download files are outdated according to the current liveworking example) . 

So i inspected the live working example and extracted the code and now it works like a charm. 

The only problem is that im not beeing able to update uniforms on realtime. 

Im only tryng to set time as a uniform so i can animate things inside the fragment shader that is running on the mask material. 

This is where i put the uniforms . if i dont change the time uniform it works as espected. the value 1.0 is entering as a uniform. 

` uniforms:{
        samplerCamera: {value: JeelizThreeHelper.get_threeVideoTexture()},
        samplerVideo: {value: videoTexture},
        videoTransformMat2: {value: spec.videoTransformMat2},
        resolution: {
          value: new THREE.Vector2(spec.canvasElement.width,
                                   spec.canvasElement.height)},
		time: { type: "f", value: 1.0 }
      }
    }); `

but i want it to be animated. 

So i´ve change maskmesh as a "global var" in the beginning of the code like this : 

`
var maskMesh = null; `

And then i added this on the callbackTrack function : 

```

function callbackTrack(detectState){
  
  
	requestAnimationFrame(render);
   maskMesh.material.uniforms.time = 3.0;
   
   JeelizThreeHelper.render(detectState, THREECAMERA);
 // console.log("Corre todos los frames esto?");
 
}
```

Im sure this does work on three.js because I already tested updating uniforms on realtime you can check it on this repository : 
https://github.com/jpupper/WebShaderGallery

but is not working on this setup using the callbackTrack function. 

Actually when I run it, it looks like is setting the maskMesh.material.uniforms.time to 0 . 

What im doing wrong?

**Comment by xavierjs** [comment]
Usually I don't answer THREE.js issues here (just issues with FaceFilter) but this one seems straightforward.
```
maskMesh.material.uniforms.time = 3.0;
```
should be replaced by:
```
maskMesh.material.uniforms.time.value = 3.0;
```
