### ISSUE TITLE
Image Capture not working

### ISSUE THREAD

**Issue by m90khan** [jeeliz/jeelizFaceFilter#257]
https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/threejs/cube2cv

Hi, 

I am having the issue capturing images from both canvases. I am using two canvases as using single was not working. 

When implementing, I could only capture the video but the model is empty. I am stuck on this one. Do you have any example of such implementation?

Thank you.

**Comment by xavierjs** [comment]
Hi,

With the 2 canvas approach,
You need to create a third canvas, an offscreen canvas for the composition and create a 2D context for this canvas.
First drawImage the FaceFilter canvas (with the video) on this third canvas,
Then enable transparency and drawImage the THREE.js canvas on this canvas.
Don't forget to initialize the three.js WebGLRenderer with `preserveDrawingBuffer: true` 
If you get the right image on the composite canvas you can then export it by using cv.toDataURL() method.

**Comment by m90khan** [comment]
```
const overlayCanvases = function (cnv1, cnv2) {
    const image = document.querySelector('.snap');

    const newCanvas = document.createElement('canvas'),
      ctx = newCanvas.getContext('2d'),
      width = cnv1.width,
      height = cnv1.height;

    newCanvas.width = width;
    newCanvas.height = height;

    [cnv1, cnv2].forEach(function (n) {
      ctx.beginPath();
      ctx.drawImage(n, 0, 0, width, height);
    });
    console.log(newCanvas.toDataURL());
    image.setAttribute('src', newCanvas.toDataURL('image/png', 0.5));
    image.classList.add('visible');

    return newCanvas.toDataURL('image/jpeg', 0.5);
  };
  
  overlayCanvases( modelCanvas, videoCanvas )
```
  
  Hi Xavier,
  Thank you for your prompt reply.
  
  I used the above function but 
  How do I turn transprancy ? by using ctx.globalAlpha = 1; ?
  Where can I initialize WebGLRenderer in this example https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/threejs/gltf_fullScreen/main.js ?
  
   Sorry, my knowledge of the three.js is limited. Thank you.

**Comment by xavierjs** [comment]
You don't need ctx.globalAlpha.
The THREE. WebGLRenderer is initialized in the Jeeliz three helper

**Comment by m90khan** [comment]
I added that inside  Jeeliz three helper and it works with my above code. 
one last thing:
I am trying to add a foreground into the three.js model canvas to the lower bottom. but it never gets added. any help in this case?

```
      // const img = new Image();
      // img.src = '/assets/models/img.png';

      // // WAIT TILL IMAGE IS LOADED.
      // img.onload = function () {
      //   fill_canvas(img); // FILL THE CANVAS WITH THE IMAGE.
      // };

      // function fill_canvas(img) {
      //   // CREATE CANVAS CONTEXT.
      //   const canvas = document.getElementById('threeCanvas');
      //   const ctx = canvas.getContext('2d');

      //   canvas.width = img.width;
      //   canvas.height = img.height;

      //   ctx.drawImage(img, 0, 0); // DRAW THE IMAGE TO THE CANVAS.
      // }
```

**Comment by xavierjs** [comment]
You need to add a sprite to the scene, textured with your image texture, with a spriteMaterial having sizeAttenuation:false and the sprite scale should be 1,1,1 to fill the whole screen if I remember well. The camera is at 0,0,0 (only the model moves), so the sprite position should be at 0,0,-1 to be forward the camera (maybe -1 is wrong, should be higher than zMin)

**Comment by m90khan** [comment]
This seems to work but it moves with the 3D model. 
Thanks, Xavier.

**Comment by xavierjs** [comment]
You need to add it directly to the three.js scene, instanced in the Three helper, not in the Object3D tracking the face

**Comment by m90khan** [comment]
Sorry, did not understand the above. you mean jeelizThreeHelper. can you give an example?

**Comment by xavierjs** [comment]
Yes the jeeliz three helper. To understand the code there you need to learn the fundamentals of THREE.js before
