### ISSUE TITLE
is it possible to give an input canvas in video settings instead of a video element?

### ISSUE THREAD

**Issue by triptu** [jeeliz/jeelizFaceFilter#259]
Hi! thanks for the amazing library. I was wondering if something like below is possible?

```js
JEELIZFACEFILTER.init({
 ...
 videoSettings: {
       canvasElement
  }
}
```

I can probably create a temp video element with captureStream to make this work, any recommendations?

**Comment by xavierjs** [comment]
Hi,
Nop, you need to handle your own web texture through the `set_inputTexture` method. Demos for face replacement in this repo are using it.
