### ISSUE TITLE
Blocking main JS thread

### ISSUE THREAD

**Issue by sofly** [jeeliz/jeelizFaceFilter#261]
Hello. I like your library! Thank you for your work.

## Expected Behavior
When initializing the library, the main js thread should not block.

## Current Behavior
The main js thread is blocked for 1-6 seconds or the page can be frozen after the init method.

## Possible Solution
Use async code inside the init function or maybe web worker.

## Context (Environment)
Any devices

## Detailed Description
<img width="1283" alt="Screenshot 2021-12-03 at 21 51 33" src="https://user-images.githubusercontent.com/9013581/144673873-407e4420-5a0c-4662-be03-b2a09ea8e5cf.png">

**Comment by xavierjs** [comment]
It depends on your config I think. I never met this issue. It should be during webgl textures initialization. Since it is not possible to do WebGL in webworkers your solution won’t work.

**Comment by sofly** [comment]
Hello @xavierjs. Thank you for your answer.  I'm very sorry. I found an issue in my project, I initialized the library when was doing hard animation. Without animation everything is OK. Thanks for you help.
