### ISSUE TITLE
Image not being rendered in the 'JeelizFacefilterFollow' div in Safari.

### ISSUE THREAD

**Issue by Bharathm1** [jeeliz/jeelizFaceFilter#264]
It is working perfectly in Chrome and firefox, but when run through Safari, the image doesn't display in the corresponding div even thought div fluctuates wrt the head movements..I have taken the code from https://github.com/ikebastuz/jeelizTest  ,

**Comment by nitinrhr200** [comment]
I am also facing the same issue.....Again me also used the react form of Jeelizfacefilter from ikebastuz/JeelizTest...It works in firefox and chrome but not in Safari. The div is getting orientations according to head movements but the image or object is not rendered.
