### ISSUE TITLE
Image not being rendered in the 'JeelizFacefilterFollow' div in Safari.

### ISSUE THREAD

**Issue by nitinrhr200** [jeeliz/jeelizFaceFilter#265]
The comedyglasses.js doesnt render the comedyglasses.png image in Safari. It is working perfectly in Chrome and firefox, but when run through Safari, the image doesn't display in the corresponding div even though when inspected, the div is being found and fluctuates wrt the head movements..I have taken the code from https://github.com/ikebastuz/jeelizTest ,...

**Comment by xavierjs** [comment]
You are using a deprecated version of Jeeliz faceFilter. Please try with the version of comedy glasses included in this Github repo, and if the problem persists, provide more information (Safari version, console logs, screenshots) so that I can figure out what happens.

**Comment by nitinrhr200** [comment]
> You are using a deprecated version of Jeeliz faceFilter. Please try with the version of comedy glasses included in this Github repo:
> 
> * Live demo: https://jeeliz.com/demos/faceFilter/demos/CSS3D/comedy-glasses/
> * Source: https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/CSS3D/comedy-glasses
> 
> If the problem persists, provide more information (Safari version, console logs, screenshots) so that I can figure out what happens.

I wanted the React demo of the same using create-react-app...Without the need of any servers...How can I get the same comedy-glasses demo in react?Is it possible?The deprecated version is actually in react form

**Comment by xavierjs** [comment]
I am not here to teach you react

**Comment by kuerm** [comment]
Hi @xavierjs 
I tested the comedy-glasses Live demo on Safari, Version 15.0 (16612.1.29.41.4, 16612). Video stays black (on Chrome it's working perfect)
No Console outs - except "INFO: JEELIZFACEFILTER IS READY"
The Comedy-Glasses picture on the upper left corner is disappearing after everything is loaded. Camera is showing that something accesses it (camera-on "light")
![Screenshot 2022-01-09 at 14 34 05](https://user-images.githubusercontent.com/28057122/148684456-f3dee254-5f2d-443f-bb49-2488c83ecea9.png)

**Comment by xavierjs** [comment]
Hi,

**Comment by xavierjs** [comment]
Hi
Do other demos work? Like this one: https://jeeliz.com/demos/faceFilter/demos/canvas2D/faceTrack/

This issue looks like a duplicate of this one: https://github.com/jeeliz/jeelizFaceFilter/issues/253
It was an issue with Safari 15.0, video could not be transferred to a WebGL Texture (it just makes a black texture without any error or warning). It was solved in Safari 15.1

**Comment by kuerm** [comment]
faceTrack looks the same - doesn't work too.
I downloaded Safari Tech Preview Release 137 (Safari 15.4, WebKit 16613.1.11.8) - which stays black too.
Unfortunately I can't download Safari Betas since I'm not an Apple Developer.

I hope that Safari 15.1 will released soon and that bug is fixed and stays fixed ;)
