### ISSUE TITLE
toggle_pause can't clear last face detection data

### ISSUE THREAD

**Issue by cucuzi** [jeeliz/jeelizFaceFilter#267]
Hello! I use demo code (canvas2D/faceTrack)
When detecting face, i get canvas base64 date and use toggle_pause(false) to stop.
But when i toggle_pause(true) to restart, the detectState is not reset.
Code:
https://codepen.io/cucuzi/pen/GRMGLoG

**Comment by xavierjs** [comment]
Hi,

It is a normal behavior. When you resume Jeeliz FaceFilter assumes that the detectState is the same as before the pause (the pause has stopped the detection loop so it has not been updated).

**Comment by cucuzi** [comment]
> Hi,
> 
> It is a normal behavior. When you resume Jeeliz FaceFilter assumes that the detectState is the same as before the pause (the pause has stopped the detection loop so it has not been updated).
Thank you reply!
So, we no idea to clear detectState? :(
Or, I must destory faceFilter When I then init again.

**Comment by cucuzi** [comment]
Oh, I get a stupid way.
When i resume faceFilter, setting a flag to clear detectState.detected.
Thank you! :)
