### ISSUE TITLE
Flickering in Video element when passing canvas stream

### ISSUE THREAD

**Issue by rohg007** [jeeliz/jeelizFaceFilter#269]
Hey, I'm trying to pass the mediastream from canvas to a video element. However, it leads to some weird flickering. I doubt if it's because of some re-renders. 

https://github.com/rohg007/JeelizFaceDrawReact/commit/3213a5cf24b5862eaf19dfbb65b397a5f29d14ec

Here's my commit on the JeelizFaceDrawReact example repo demonstrating the same.

**Comment by xavierjs** [comment]
Please uncomment `enableAsyncReadPixels: false` in `App.js`

Currently async readpixels is enabled by default, so maybe sometimes the canvas frame is read when readpixels is over and then the video image is copied, and sometimes readpixels is still pending and the context fenced and a blank frame is copied.

It fixed the bug on my side.

**Comment by rohg007** [comment]
I uncommented the given flag but the flickering still persists on my end.

**Comment by xavierjs** [comment]
You need to uncomment it then **reload the page** (hot reload does not take account of the change).

**Comment by xavierjs** [comment]
Did it work?

**Comment by rohg007** [comment]
Yes, it did work, but I suspect that it still doesn't work for some of the users. Will reopen the issue, as soon as I catch something.
