### ISSUE TITLE
Refactor the dependency 

### ISSUE THREAD

**Issue by dupasj** [jeeliz/jeelizFaceFilter#271]
Hello !

This is not to report a bug but to suggest you an improvement of your dependency.
Are you interested by a big refactor of your dependency ? (I will include ThreeJS helper, within the core module in typescript. I never do some babylon project so I can't really do it :/)

I used twice our dependency, and I always copy/paste the projects files instead of use the package directly.

**Comment by xavierjs** [comment]
Hi @dupasj 

Do you mean for the NPM package used in the https://github.com/jeeliz/jeelizFaceFilter/tree/master/reactThreeFiberDemo
Or the static JavaScript demos?

**Comment by dupasj** [comment]
> Hi @dupasj
> 
> Do you mean for the NPM package used in the https://github.com/jeeliz/jeelizFaceFilter/tree/master/reactThreeFiberDemo Or the static JavaScript demos?

Hi !

**Comment by dupasj** [comment]
I mean for the NPM package.

**Comment by xavierjs** [comment]
Sure I would be interested :)
But I would prefer to keep Three.js helper either outside the package, or to put it in a separate package.
Indeed, even if FaceFilter is mostly used with Three.js, this lib is framework agnostic.

**Comment by dupasj** [comment]
Yes sure ! It's what I want to do !

**Comment by dupasj** [comment]
Little outscoped question ^^'
Will you provide more AR really experience ? Like foot tracking, body tracking, surface tracking... ?!

**Comment by xavierjs** [comment]
* Jeeliz brand will be focused on glasses virtual try-on, especially through the Jeeliz VTO widget 
* Jeeliz FaceFilter and Jeeliz Weboji will still be maintained and improved,
* Enhanced experiences are provided by WebAR.rocks brand ( https://github.com/webAR-rocks ), especially:

  * WebAR.rocks.face has a similar interface to Jeeliz FaceFilter, except it outputs the position of face landmarks and the pose is computed differently. It gives access to new use-cases: high precision virtual try-on for hats, headphones, helmets, glasses, lipstick and makeup virtual try-on, deformable masks
  * WebAR.rocks.hand is focused on hand detection and tracking, I am actively working on it. It can be used for hand based navigation, bracelet/wristwatch and ring VTO, hand object manipulation
  * WebAR.rocks.object and WebAR.rocks.image are for objects or images detection and tracking, but their use is not fully standalone (it requires often custom neural network training), except for some use-cases like keyboard based SLAM or cup detection for example.
  * surface tracking does not suit very well to neural network-based detection, and furthermore it will come through WebXR (as soon as Apple will decide to implement it correctly), so I have no plans for that
  * body tracking is also not in my focus,
  * I am working on foot tracking but the results are not good enough for commercial use yet.

**Comment by dupasj** [comment]
Thus projects looks really cool !
Could I have the unminified source of the project ? I will try to merge all thus projects in one ;)

**Comment by dupasj** [comment]
All right,
I can't merge thus projects in one if I can't view the unminfied code, I will do my best. 
If you don't want to provide thus lines of code for reasons of fairness, we can sign confidentiality agreements if you want.

I send you an email with mores details.
Cheers
