### ISSUE TITLE
With the latest version of threeJS library , camera video is not rendering 

### ISSUE THREAD

**Issue by arunscbe** [jeeliz/jeelizFaceFilter#272]
Hi, While upgrading the threeJS library to the latest version, the camera video is not rendering, but the head tracking is happening fine and model is loading. please check the below git URL for the reference.

URL : [AUGUSTA - CAP (arunscbe.github.io)](https://arunscbe.github.io/capar/)
![cap](https://user-images.githubusercontent.com/12148167/175944988-f972d5c9-bd70-4e2d-b021-88f2ca422458.JPG)

**Comment by xavierjs** [comment]
Hi,

Please use the 2 canvases approach:
https://github.com/jeeliz/jeelizFaceFilter#1-or-2-canvas
