### ISSUE TITLE
FaceFilter face model transparency issue

### ISSUE THREAD

**Issue by arunscbe** [jeeliz/jeelizFaceFilter#274]
Hi,
     While updating the threejs library to R.142, the shadermaterial of the face model becoming black , transparency is not working properly, and have used 2 canvas approach , below image for reference.
![mask](https://user-images.githubusercontent.com/12148167/176414555-1ab42b20-51f8-4964-be92-94721f20cc7a.JPG)

**Comment by xavierjs** [comment]
Hi please share your code

**Comment by arunscbe** [comment]
LINK : https://github.com/arunscbe/capARMask

**Comment by xavierjs** [comment]
In your main.js, set:
```
const mat = new THREE.ShaderMaterial({
      vertexShader: vertexShaderSource,
      fragmentShader: fragmentShaderSource,
      transparent: false,
      //flatShading: false,
      uniforms: {
        samplerVideo:{ value: JeelizThreeHelper.get_threeVideoTexture() },
        // videoTransformMat2: {value: spec.videoTransformMat2}
      },
      colorWrite: false
    });
```
I close the issue since it is not an issue with Jeeliz FaceFilter but with your THREE.js code.
