### ISSUE TITLE
can i use  navigator.mediaDevices.getUserMedia instead of the camera 

### ISSUE THREAD

**Issue by Baraa-Baba** [jeeliz/jeelizFaceFilter#276]
the reason is I am building something like omegle and I send the video as stream so how could I use it instead of using the webcam
```
 navigator.mediaDevices.getUserMedia({ video: true, audio: true }).then(
      (newStream) => {
//can I use newStream as the video 
      })
```

**Comment by xavierjs** [comment]
Read the doc: https://github.com/jeeliz/jeelizFaceFilter#optional-init-arguments
