### ISSUE TITLE
Multiple filters using .class instead of #ids.

### ISSUE THREAD

**Issue by PUShAUNE** [jeeliz/jeelizFaceFilter#28]
First of all, thank you for the hard work you did and for sharing it :)

**Is your feature request related to a problem? Please describe.**
I am trying to make a photobooth where users can choose multiple filters (like hats, glasses, jewelry), and activate or desactivate some.
I'm using CSS3, which target an id:
`DIV=document.getElementById('jeelizFaceFilterFollow');`

**Describe the solution you'd like**
It would be nice to create as many as wanted tags, and to target them with a class, or with multiple ids.

**Comment by xavierjs** [comment]
Hi,

You can do it, you only have to change the code in https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/CSS3D/div/demo_div.js

This is not very difficult, you need to learn how to manipulate the DOM with JavaScript
