### ISSUE TITLE
when set canvas width < height the face position is deviation

### ISSUE THREAD

**Issue by ouzhou** [jeeliz/jeelizFaceFilter#29]
when i set `<canvas width="1080" height="1920"></canvas> `
i find the face position downward migration
i tried using JEEFACEFILTERAPI.resize() but it not work
:)

**Comment by ouzhou** [comment]
oh 
just use `y = y*(1920/1080)` can fix 
i guess you just use the width of the canvas as the max size

**Comment by xavierjs** [comment]
I do not understand your issue. Can you post a screenshot and a more detailed code chunk so that I can help you?

There is an example including canvas resizing, the "GLTF fullscreen demo".
You should call JEEFACEFILTERAPI.resize() after the resizing.

**Comment by ouzhou** [comment]
i create a repo, thanks for your reply
https://github.com/ouzhou/face

**Comment by ouzhou** [comment]
i just set canvas height higher than its width, and use your canvas2d demo

**Comment by xavierjs** [comment]
So you have to change the scale of the detection window according to the new aspect ratio
