### ISSUE TITLE
Too much jittering when using fact filter

### ISSUE THREAD

**Issue by Kimmydoray** [jeeliz/jeelizFaceFilter#290]
Hello Jeeliz,

I have check three js base demos and all of it is jittering too much.
Mind-ar filter(https://github.com/hiukim/mind-ar-js), they are using one euro filter for it: https://hiukim.github.io/mind-ar-js-doc/quick-start/tracking-config. to stabilize the image. Is their possibility that we can integrate one euro filter in the app?

Best regards,
Edzel

**Comment by xavierjs** [comment]
Hi Edzel,

**Comment by xavierjs** [comment]
Hi Edzel,

Sure, you are welcome to submit a PR to improve the stabilization in the Three.js helper.
All the code to compute the Three.js pose is open source, you just have to implement your filter there.

Best regards,
Xavier

**Comment by Kimmydoray** [comment]
Hello Xavier,

I would like to ask if do you already set a stabilization for the three.js?

Best regards,
Edzel

**Comment by xavierjs** [comment]
Hi,

There is a slight stabilization for the pose inside the lib, not specific to Three.js, but you can implement your own if it is not enough

Best,
Xavier

**Comment by tausif-fardin** [comment]
Can I detect body instead of face?
