### ISSUE TITLE
README not updated for Three.js JSON

### ISSUE THREAD

**Issue by RobinLasserye** [jeeliz/jeelizFaceFilter#294]
Hello JeelizFaceFilter,

I'm working on three js Face Filter. To begin I used the gltf demo to test it and It works correctly.

Netherless, I tried more difficult demos like the json provided demos like the werewolf. I would like to recreate my own facefilter with the blender files examples. But problem : the README.md is outdated about it.
https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/threejs/README.md

The repo threejs doesn't provide Blender exporter to export the model in json anymore.

So it seems impossible to recreate its own facefilter by using json, or if it's the case, it's not explicated in the README.

**Comment by xavierjs** [comment]
Hi, 

It is done. Please see the updated README. If you want to recreate your own face filters, I strongly encourage you to use GLTF file format instead of THREE legacy JSON file format, and also to use 2 canvas instead of 1 (see https://github.com/jeeliz/jeelizFaceFilter/#optimization )
