### ISSUE TITLE
How could I apply face detection to still images?

### ISSUE THREAD

**Issue by highlyinteractive** [jeeliz/jeelizFaceFilter#298]
Hi,

I've been playing around with this library - it's great to find such a lightweight piece of code.

This is more of an enhancement request than a bug report, but I've been trying to apply the face detection to a still image instead of a video stream, but it doesn't seem to be possible.

So is there any way to detect a face in a still image?

I can think of a few use cases that would benefit from this:

- Photo filters is the most obvious
- Creating a gallery of filters by applying the filter to a still frame to visualise it
- Validating poses in user-uploaded photos (this is what I'm hoping to use it for)

Perhaps it's not possible for incredibly complex and sensible reasons. Perhaps it is possible & I've misread the documentation?

Any help or advice would be greatly appreciated!

Thanks

**Comment by xavierjs** [comment]
Hi,

Thank you for your interest in this lib.

It is possible, please see this issue:
https://github.com/jeeliz/jeelizFaceFilter/issues/146

And also the `set_inputTexture` and `reset_inputTexture` methods in the README:
in https://github.com/jeeliz/jeelizFaceFilter/#miscellaneous-methods

If you need more help I can provide development services and support, you can contact me at xavier__at__jeeliz.com
