### ISSUE TITLE
The camera can't recognize the face at a little distance

### ISSUE THREAD

**Issue by Reckless1998** [jeeliz/jeelizFaceFilter#305]
In the case of three.js, the face will not be recognized if it is a little far away from the camera. If it is close to the camera, the face can be recognized. Can I use a value to control the recognition distance?

**Comment by xavierjs** [comment]
You can use the `scanSettings` init parameter or the `set_scanSettings` post-init method to tune face search - see https://github.com/jeeliz/jeelizFaceFilter#miscellaneous-methods

Related to https://github.com/jeeliz/jeelizFaceFilter/issues/127#issuecomment-534593145

**Comment by Reckless1998** [comment]
Thanks a lot!! I only change scanSettings.scale0Factor to a lower value and it works very good! 😃 I will close this issue.
