### ISSUE TITLE
toggle_pause doesn't work with a specific sequence

### ISSUE THREAD

**Issue by marcusx2** [jeeliz/jeelizFaceFilter#307]
I am trying out toggle_pause, and there seems to be a specific case where it doesn't work as expected.

Here's a table of tests of pause/unpause. For example `true true/false true` means I called `toggle_pause(true, true)` to pause, then `toggle_pause(false, true)` to unpause

true true/false true -> works
true true/false false -> doesn't work.
true false/false true -> works
true false/ false false -> works

I don't know if this is working as intended, but it seems wrong. I think the second parameter should be ignored if I am unpausing and the video stream should come back, right? But if I call `true true/false false`, the screen stays frozen, the video stream seemingly doesn't come back.

**Comment by xavierjs** [comment]
Hi

if you call toggle_pause and you shut off the video stream (true, true), then when resuming you need to turn on the video stream… calling the function with true true then false false is nonsense. The second parameter should have the same value for both calls.
