### ISSUE TITLE
Changing the neural net throws error at runtime

### ISSUE THREAD

**Issue by marcusx2** [jeeliz/jeelizFaceFilter#308]
If you get the threejs cube example, and change the _init_faceFilter_ function to

```
function init_faceFilter(videoSettings){
  JEELIZFACEFILTER.init({
    followZRot: true,
    canvasId: 'jeeFaceFilterCanvas',
    NNCPath: 'NN_LIGHT_1.json', // root of NN_DEFAULT.json file
    maxFacesDetected: 1,
    callbackReady: async function(errCode, spec){
      if (errCode){
        console.log('AN ERROR HAPPENS. ERR =', errCode);
        return;
      }

      await JEELIZFACEFILTER.destroy();

        JEELIZFACEFILTER.init({
            followZRot: true,
            canvasId: 'jeeFaceFilterCanvas',
            NNCPath: 'NN_4EXPR_2.json', // root of NN_DEFAULT.json file
            maxFacesDetected: 1,
            callbackReady: function (errCode, spec) {
                if (errCode) {
                    console.log('AN ERROR HAPPENS. ERR =', errCode);
                    return;
                }

            },

            // called at each render iteration (drawing loop):
            callbackTrack: function (detectState) {
                JeelizThreeHelper.render(detectState, THREECAMERA);
            }
        }); //end JEELIZFACEFILTER.init call
        
    },

    // called at each render iteration (drawing loop):
    callbackTrack: function(detectState){
      JeelizThreeHelper.render(detectState, THREECAMERA);
    }
  }); //end JEELIZFACEFILTER.init call
}
```

so that it is first initialized with the _NN_LIGHT_1_ neural network, but later changed to _NN_4EXPR_2_ (I destroy and init again), you will get the following error on the console (give it a few seconds)

<img width="1393" alt="image" src="https://github.com/jeeliz/jeelizFaceFilter/assets/5656275/3414c02e-4581-4e51-9ca2-cbee20a8b19d">

**Comment by xavierjs** [comment]
Hi @marcusx2 
Thank you for this detailed bug report. I was able to reproduce it and I it should be fixed by the last commit.

**Comment by marcusx2** [comment]
Thanks that worked!

**Comment by xavierjs** [comment]
@marcusx2 Hi Marcus

When you do something very cool like a Unity plugin for Jeeliz Facefilter, feel free to tell it :) !
I just did a bit of advertisement:

* on the readme of this repo: https://github.com/jeeliz/jeelizFaceFilter#unity
* twitter: https://twitter.com/WebARRocks/status/1706318244842230164
* linkedin: https://www.linkedin.com/posts/jeeliz_unity-facefilter-webar-activity-7112080164007636993-y2Ty?utm_source=share&utm_medium=member_desktop

**Comment by marcusx2** [comment]
Hi @xavierjs

> When you do something very cool like a Unity plugin for Jeeliz Facefilter, feel free to tell it :) !

I did! I linked to your jeeliz website and this repo

<img width="764" alt="image" src="https://github.com/jeeliz/jeelizFaceFilter/assets/5656275/c68a2fc7-8c1f-4157-b18a-cd5060cb4cee">

Thanks for the advertisement!

**Comment by xavierjs** [comment]
Hi @marcusx2 

Sure I noticed the link thanx, by *feel free to tell it* I did not mean to add the jeeliz facefilter link but just to tell informally, I am always glad to test and post stuff about stuff made using Jeeliz or WebAR.rocks libs.
