### ISSUE TITLE
How can we stop preview/close camera in javascript function?

### ISSUE THREAD

**Issue by VedantBH** [jeeliz/jeelizFaceFilter#31]
I have a button, javascript function is called onclick. I want to stop the preview in javascript function.

**Comment by xavierjs** [comment]
you can stop the rendering loop to not use resources, but you cannot release the camera.

**Comment by andrewlphilpott** [comment]
Would it be possible to get a method added to release the camera? The use case for the app I'm using this in makes it pretty important to disable the camera after it's being used.

If it's not something that will be added, I can just use a workaround I made by slightly modifying the `jeelizFaceFilter.js` file, but ideally I would like to avoid changing your scripts.

**Comment by xavierjs** [comment]
Hi,

Indeed, this feature is currently not implemented in this Github repository.
However, @Jeeliz we would be happy to help you to adapt our libraries to fit your needs.
You can ask for this specific development service to contact__at__jeeliz.com and we will send you a proposal. 

Best regards,
Xavier

**Comment by andrewlphilpott** [comment]
If I made a PR, would you be willing to consider adding it?

**Comment by xavierjs** [comment]
Sure thanx
