### ISSUE TITLE
Background colour changes to yellow when face detected during night.

### ISSUE THREAD

**Issue by vbh25** [jeeliz/jeelizFaceFilter#34]
![capture](https://user-images.githubusercontent.com/19422397/44993336-d6a7d780-afb7-11e8-912f-66f5f432c74c.PNG)

**Comment by xavierjs** [comment]
This issue does not comesfrom the lib, and I have no information to debug it.

**Comment by vbh25** [comment]
ohh, okay.

**Comment by vbh25** [comment]
awesome project and very nice support from you guys.
