### ISSUE TITLE
Can we find neckpoints having face coordinates i.e. faceCoo.x, y, z and detectface.rx, ry, rz?

### ISSUE THREAD

**Issue by vbh25** [jeeliz/jeelizFaceFilter#35]

**Comment by xavierjs** [comment]
Hi,

You have to:
* match a 3D model with the user's face like in the Matrix Facefilter tutorial
* the 3D model is moved with the detectstate
* you take the coordinates of the point matching the neck for example and you multiply it with the wordmatrix.

I suggest you, before working with this library, to learn basics of 3D programming. You can start here: http://webglacademy.com/ or there: http://learningwebgl.com/blog/?page_id=1217

**Comment by vbh25** [comment]
Thanks a lot

**Comment by vbh25** [comment]
Can you please explain bit more to achieve this in canvas2D facetrack ?

**Comment by vbh25** [comment]
how to get coordinates of points matching the neck? and where is the wordmatrix?

**Comment by xavierjs** [comment]
Hi,

I am sorry but this is not a beginner 3D forum. Your question is not about faceFilter.
I have a lot of work, I put detailed explanation about all detectFace properties, and there are many commented demos to have examples. I don't have time to explain basic 3D concepts like projection or the worldmatrix. You have to learn them by yourself.

**Comment by vbh25** [comment]
okay, sorry & thank you

**Comment by vbh25** [comment]
The script.js here http://webglacademy.com/courses.php?courses=0_1_20_2_3_4_23_5_6_7_10#20
is lagging while scrolling.

**Comment by xavierjs** [comment]
Hi,

This is because you are running a very heavy shader (I suppose you are in the last steps and you have clicked on RUN button).
So your resources are so busy that it makes the DOM slow.
In order to force the computer to not fully use the resources for the shader, you can replace ` window.requestAnimationFrame(animate);` on script.js by:
```
 window.requestAnimationFrame(tickAnimate);
```

and declare `tickAnimate` just after `animate` by:

```
var tickAnimate=function(timestamp){
   setTimeout(animate.bind(null, timestamp), 5); //5 is short time in ms where the browser is idle so it can refresh easily
}
```
