### ISSUE TITLE
3D model shakes on iOS 12

### ISSUE THREAD

**Issue by whilemouse** [jeeliz/jeelizFaceFilter#38]
First, thanks for this good library.

My environment:
- Device: iPhone6s, iPhoneX
- OS: iOS 12

NNC Version:
- NNC.json(default neural network in jeelizFaceFilter tag 1.1)

I was using it well on iOS 11. but I updated it to iOS 12 and I found the 3d model shaking. Is it a problem with ios12?

**Comment by xavierjs** [comment]
No this is not a pb with IOS12,
Maybe light conditions. I cannot do nothing with your bug report.
Try to play with the stabilization parameters, this is explained in the readme

**Comment by whilemouse** [comment]
thanks~
