### ISSUE TITLE
Multiple face tracking.

### ISSUE THREAD

**Issue by rodrigograca31** [jeeliz/jeelizFaceFilter#4]
Amazing library!
Nice to finally see an alternative to the existing (slow) ones.

Is there any intent to add the option to track multiple faces in the future?

Thanks.

**Comment by xavierjs** [comment]
Hi Rodrigo,
Yes, we will add multiple face tracking for the next month. But it may slow down the tracking (if you track 2 faces for example there will be 2X less computing power per face for the tracking).

**Comment by xavierjs** [comment]
Hello,

The multi face detection has been added :). It is very new so maybe there are still some bug left.
I have put the doc in the README.md of the repo.
There is currently only 1 demo, https://jeeliz.com/demos/faceFilter/demos/threejs/multiCubes/ . It detected simultaneously 4 faces max. The code is included in the repo.
I will add a faceswap soon.

**Comment by rodrigograca31** [comment]
Thats awesome! We can close this now.......
