### ISSUE TITLE
Camera doesn't open in some mobile phone browsers.

### ISSUE THREAD

**Issue by vbh25** [jeeliz/jeelizFaceFilter#40]
I tried in Moto G4 Play and Lenovo phone. The Camera is not opening even after 2mins.

**Comment by xavierjs** [comment]
I don't have a moto G4 play and i don't have a lenovo phone, so what you want me to do with such an incomplete bug report?
Give some console log, browser version etc if you want to be useful.
Read the readme of the repo first:
If a compatibility error is triggered, please post an issue on this repository. If this is a problem with the webcam access, please first retry after closing all applications which could use your device (Skype, Messenger, other browser tabs and windows, ...). Please include :

> 
> a screenshot of webglreport.com - WebGL1 (about your WebGL1 implementation),
> a screenshot of webglreport.com - WebGL2 (about your WebGL2 implementation),
> the log from the web console,
> the steps to reproduce the bug, and screenshots.



Thx

**Comment by vbh25** [comment]
Okay. thanks
