### ISSUE TITLE
Face detection incorrect for the first few frames. 

### ISSUE THREAD

**Issue by vbh25** [jeeliz/jeelizFaceFilter#44]
I am trying with canvas2d face track example. Face rectangle comes somewhere below the face for the first few frames. Is there any reason for it?
![capture](https://user-images.githubusercontent.com/19422397/46606067-3ba39f80-cb19-11e8-89c9-80cc67d89cec.PNG)

**Comment by xavierjs** [comment]
Hi,

Sometimes the neural network got wrong...

You can try to put a higher detection threshold.
On https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/canvas2D/faceTrack/demo_faceTracking.js
you have:
`if (detectState.detected>0.6){`

you can try to put:

`if (detectState.detected>0.92){`
