### ISSUE TITLE
Video stopped when fullscreen mode with viewport

### ISSUE THREAD

**Issue by whilemouse** [jeeliz/jeelizFaceFilter#45]
First, thanks for this good library.

**Describe the bug**
I used three.js demo and modified. video stopped when fullscreen mode with viewport. Probably it happened where only old iPhone.

**To Reproduce**
1. Go to source file 'demos/threejs/miel_pops/index.html'
2. Change Code

* demos/threejs/miel_pops/index.html
    * add **viewport**
```html
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
```

* demos/threejs/miel_pops/demo.js
    * add **isFullScreen: true,**
```` javascript
function main(){
    JeelizResizer.size_canvas({
        canvasId: 'jeeFaceFilterCanvas',
        isFullScreen: true,
        callback: function(isError, bestVideoSettings){
            init_faceFilter(bestVideoSettings);
        }
    })
}
````

2. open safari -> responsive design mode -> select iPhone SE
3. open 'demos/threejs/miel_pops/index.html'
4. Stopped video

**Expected behavior**
Playing video

**Screenshots**
I don't upload. because screenshot can't know playing or stopped.

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra 10.13.3 
 - Browser [responsive design mode iPhone SE in safari(11.0.3)]

**Smartphone (please complete the following information):**
 - Device: [iPhone6s, iPhone SE]
 - OS: [iOS 12.0.1]
 - Browser [safari 11.0.3]

**Additional context**
My test device
* Video playing device
    * iPhone 8(responsive design mode in mac os safari) : video playing
    * Mac OS(safari) : video playing
* Video stopped device
    * iPhone 6s(mobile safari): video stopped
    * iPhone SE(responsive design mode in mac os safari) : video stopped
    * galaxy note 9(mobile chrome): video playing

**Comment by whilemouse** [comment]
By adding this code will cause the video to play. It should work with **setTimeout**

````javascript
if (document.querySelector('video') !== null) {
    setTimeout(function () {
        document.querySelector('video').play();
     }, 100);
}
````

````javascript
function init_faceFilter(videoSettings){
    JEEFACEFILTERAPI.init({
            ...
        callbackReady: function (errCode, spec) {
            ...
        if( document.querySelector('video') !== null) {
            setTimeout(function () {
                document.querySelector('video').play();
            }, 100);
        }
            init_threeScene(spec);
        }, // end callbackReady()
    ...
}
````

**Comment by xavierjs** [comment]
It should work now :)

**Comment by whilemouse** [comment]
It works. thank you for a quick and accurate response. :)

**Comment by xavierjs** [comment]
Related to #14
