### ISSUE TITLE
Unity 3D intergration

### ISSUE THREAD

**Issue by enemali** [jeeliz/jeelizFaceFilter#49]
is there anyway we can integrate this with Unity 3d?

**Comment by xavierjs** [comment]
Hi,

I think it would be difficult because unity is made using C# and I don't know if it is possible to build stuffs using JavaScript/WebGL with Unity. And it is not planned since Unity is a proprietary tech.

**Comment by johanwitters** [comment]
I'm not an expert on unity not jeezil, but I'd imagine using a webview could do the trick

**Comment by xavierjs** [comment]
Hi,

Unity is a very nice 3D Engine, but in my opinion it is too bloated to work properly in a web context. THREE.JS is more lightweight. It may be possible to do this with a webview but it is not a clean solution. With IOS for example webviews have restrictions (on IOS11 it is not possible to access to the camera from them, I don't know for IOS12).

**Comment by enemali** [comment]
Thanks for all your inputs
