### ISSUE TITLE
Safari 12 on Mojave 10.14 error

### ISSUE THREAD

**Issue by andrewdeutsch** [jeeliz/jeelizFaceFilter#52]
**Describe the bug**
Jeeliz is throwing 3 errors on the new Safari in Mojave 10.14 available in the App Store.

- AN ERROR HAPPENS. SORRY BRO :( . ERR = – "WEBCAM_UNAVAILABLE" https://jeeliz.com/demos/faceFilter/libs/tween/v16_3_5/Tween.min.js.map
- [Error] Failed to load resource: the server responded with a status of 404 () (Tween.min.js.map, line 0)
- WebGL: INVALID_OPERATION: texImage2D: type HALF_FLOAT_OES but ArrayBufferView is not NULL

**To Reproduce**
1. Go to Safari 12 on Mojave 10.14
2. Load any Jeeliz demo (https://jeeliz.com/demos/faceFilter/demos/threejs/butterflies/)
3. Open console
4. You'll get the page with no camera.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1167722/47732953-9bcfc200-dc3d-11e8-8a53-12d4afcc2f5a.png)

**Desktop (please complete the following information):**
 - OS: Mojave 10.14
 - Browser  Safari
 - Version  12

**Smartphone (please complete the following information):**
 Desktop issue only

Thanks!

**Comment by xavierjs** [comment]
Hi Andrew,

Thank you for this detailed report.
The 2 errors here are not important, the first is not important because Tween.min.js is here and the second is when we test the real webgl capabilities.

But the WEBCAM_UNAVAILABLE is a problem with WebRTC I think.
I have changed recently the WebRTC internal helper to solve IOS12 problems and I forgot to update FaceFilter. This is done now :). Can you try the basic boilerplate demo here: https://jeeliz.com/demos/faceFilter/demos/threejs/cubeWithHelper/

Otherwise are you sure there is not another application using the webcam? Like Skype?

Thank you very much

**Comment by andrewdeutsch** [comment]
Thanks for the quick reply! 
Unfortunately this link: 
https://jeeliz.com/demos/faceFilter/demos/threejs/cubeWithHelper/ 
isn't working in Safari or Chrome.
It's strange because it's not showing any console errors.
![image](https://user-images.githubusercontent.com/1167722/47740221-a72ae980-dc4d-11e8-92be-9ae606c6c267.png)

**Comment by xavierjs** [comment]
It is hard to debug for me because I don't have a mac and the mac computers I can use don't have Mojave :(.

Does other WebRTC demos work ?
Like: https://webrtc.github.io/samples/src/content/getusermedia/resolution/
or: https://webrtc.github.io/samples/src/content/getusermedia/gum/

**Comment by andrewdeutsch** [comment]
The VGA and QVGA demos work, yes. HD and above don't.

**Comment by xavierjs** [comment]
Good news, there will be a solution to this problem so :).
Can you give me the JavaScript console log of: https://jeeliz.com/tests/libGetUserMedia/
It should display the <video> image with the same settings than faceFilter + it logs the video constraints which succeed or fail.

Thank you very much

**Comment by andrewdeutsch** [comment]
Sounds good! 
INFO in lib_getUserMedia() - get() : constraints = {"video":{"facingMode":{"ideal":"user"},"width":{"min":480,"max":1280,"ideal":800},"height":{"min":480,"max":1280,"ideal":600}},"audio":false}
lib_getUserMedia.js:30 INFO in lib_getUserMedia - get_raw(): videoStream got
lib_getUserMedia.js:34 INFO in lib_getUserMedia - get_raw() : video.onloadedmetadata dispatched
lib_getUserMedia.js:34 INFO in lib_getUserMedia - get_raw() : playPromise accepted
lib_getUserMedia.js:29 INFO in lib_getUserMedia - get_raw(): callbackSuccess called with constraints=
lib_getUserMedia.js:29 {"facingMode":{"ideal":"user"},"width":{"min":480,"max":1280,"ideal":800},"height":{"min":480,"max":1280,"ideal":600}}
(index):26 callbackSuccess
(index):27 resolution : 0 0
(index):28 resolution2 : 800 600

**Comment by xavierjs** [comment]
Hi Andrew,

Can you retry https://jeeliz.com/demos/faceFilter/demos/threejs/cubeWithHelper/ (After cleanning the cache). I have improved the Safari detection in order to apply Safari polyfills.

Thank you very much

**Comment by xavierjs** [comment]
Great :) :) :) I just have to deploy this fix over all Jeeliz libs (Weboji, JeelizAR, ...) 
Thank you very much for you help!

**Comment by sonidiaz** [comment]
Hi,

I do not know if you have already implemented the revision in the Jeeliz libs but
doing some tests, I have seen that the projects / demo of jeelizFaceFilter and jeelizWeboji throw this error ** WebGL: INVALID_OPERATION: texImage2D: type HALF_FLOAT_OES but ArrayBufferView is not NULL **
Safari 12 / MacOS Mojave

Thanks!
