### ISSUE TITLE
FaceFilter and VTOWidget diff

### ISSUE THREAD

**Issue by whilemouse** [jeeliz/jeelizFaceFilter#54]
Hi. @xavierjs 
Always thanks for your project. 

I used jeelizFaceFilter and [VTOWidget](jeelizGlassesVTOWidget), and found that VTOWidget is better for recognition rate and recognition rate.

Do you plan to make FaceFilter as fast and accurate as VTOWidget? If so, could you tell me a rough schedule? I'm sorry if it felt like you were in a hurry. I just want to know if it's scheduled.

**Comment by xavierjs** [comment]
Hi @whilemouse

I think there are 3 factors:

* The neural network used for the VTO widget benefits of some last improvements of our tech. I have not trained again the neural net of FaceFilter but I will do. Training takes a long time and we don't have a lot of training slots,
* The VTO widget has a 100% GPU workflow. On the CPU side it is not even possible to know if the face was detected or not. So we don't have to synchronize CPU and GPU with GL.readpixels, which is slow. But then it does not use THREE.JS but a custom 3D engine, where the movements matrices are computed into the vertex shader from neural network outputs. It is very optimized but hard to handle.
* On some demonstrations of FaceFilter you can still optimize the detection or tracking, by playing with the face detection threshold or the stabilization settings (look for "set_stabilizationSettings" in the README". But it is still hard to make the balance between slow but very stabilized tracking and fast but shaky tracking.

**Comment by whilemouse** [comment]
Thanks. :)
