### ISSUE TITLE
Eyebrow motion detection?

### ISSUE THREAD

**Issue by andrewdeutsch** [jeeliz/jeelizFaceFilter#55]
Is adding eyebrow motion detection on the roadmap? I have a feeling it isn't available in the current library but thought I'd ask. Thanks.

**Comment by xavierjs** [comment]
It is not available currently, but:

* It is included in Jeeliz Weboji (https://github.com/jeeliz/jeelizWeboji)
* I am working on FaceFilterLM, the landmarks based version of FaceFilter. There will be landmarks on the eyebrows on the final version. I hope to release in the middle of November.

I can launch the training of a new neural net for FaceFilter with this feature if you really need it :)

**Comment by andrewdeutsch** [comment]
It would be great to have it soon. The mouth movement is very popular on the projects we've used it, so to have other ways to interact we'd be able to offer more options. 
FaceFilterLM is a great idea. Will it be able to handle make-up try ons?

**Comment by xavierjs** [comment]
I will launch a training by the end of the week with eyebrows + mouth opening detection.
FaceFilterLM will be able to handle make-up try-ons :) . I have planned to add an helper for this feature.

**Comment by Dok11** [comment]
@xavierjs are you planing write article about this work with collecting training dataset and etc?

**Comment by andrewdeutsch** [comment]
Great news @xavierjs . :) Thanks!
