### ISSUE TITLE
Possibility to change source (videoElement) after init

### ISSUE THREAD

**Issue by Titoine** [jeeliz/jeelizFaceFilter#59]
**Is your feature request related to a problem? Please describe.**
As It's mentioned in other issues, It's not possible to destroy and re-init.
But we have to pass the source at the init and can't change it after that.

**Describe the solution you'd like**
Possibility to change the source (videoElement).

**Additional context**
The simplest example is when you want to switch from front to back camera. 
But I could happen when you want to switch from a video to an image.

Only way I could do that now is using jeelizFaceFilter globally and with a 'global' canvas. It's possible but a bit 'hacky' when using it with React.

**Comment by xavierjs** [comment]
Hi,

I have just added the method `JEEFACEFILTERAPI.update_videoElement(videoElement, callback)` at this purpose.
I did a little test and it works :). Tell me if it works for you.

Best,
Xavier

**Comment by HZCTony** [comment]
> Hi,
> 
> I have just added the method `JEEFACEFILTERAPI.update_videoElement(videoElement, callback)` at this purpose.
> I did a little test and it works :). Tell me if it works for you.
> 
> Best,
> Xavier

hello, can you paste your code to show how to pass the videoElement in JEEFACEFILTERAPI.update_videoElement ? Thanks!
