### ISSUE TITLE
Rear Camera doesn't open

### ISSUE THREAD

**Issue by vbh25** [jeeliz/jeelizFaceFilter#65]
JEEFACEFILTERAPI.init({
    canvasId: 'jeeFaceFilterCanvas',
    NNCpath: '../../../dist/', //path to JSON neural network model (NNC.json by default)
    callbackReady: function(errCode, spec){
        if (errCode){
            console.log('AN ERROR HAPPENS. ERROR CODE =', errCode);
            return;
        }
        [init scene with spec...]
        console.log('INFO: JEEFACEFILTERAPI IS READY');
    }, 
    callbackTrack: function(detectState){
        //render your scene here
        [... do something with detectState]
    }, 
	videoSetting: {
          'facingMode': 'environment', //to use the rear camera, set to 'environment'
          'idealWidth': 800,  //ideal video width in pixels
          'idealHeight': 600, //ideal video height in pixels
          'minWidth': 480,    //min video width in pixels
          'maxWidth': 1280,   //max video width in pixels
          'minHeight': 480,   //min video height in pixels
          'maxHeight': 1280,  //max video height in pixels,
          'rotate': 0         //rotation in degrees possible values: 0,90,-90,180
    }
});//end init call

I am using this code. It opens front camera only in phones.

Can you please check?

**Comment by xavierjs** [comment]
Hi @vbh25 

The current getUserMedia API helper try to get the video stream with the given constraints.
If it is not possible, it will downgrade the constraints in order to get a video stream in all cases.

At some point, it will remove the facingMode:env (after trying the closest resolutions for the video).
I may have found the bug. Can you check: https://jeeliz.com/tests/libGetUserMedia3/

Thank you

**Comment by vbh25** [comment]
This link works, it opens rear camera. 
Sorry, I dint get "I may have found the bug...".
Is there any way to make it work in jeelizFaceFilter examples?

**Comment by xavierjs** [comment]
Hi,

I just wanted to get the problem solved on the getUserMedia helper before rebuilding FaceFilter, that's why I submited the link.
Since it work, I am building facefilter and commit the modif now :)

**Comment by vbh25** [comment]
Okay, thank you

**Comment by xavierjs** [comment]
I suppose it is working well :) Otherwise don't mind to re-open this issue
