### ISSUE TITLE
Any way we can create a gif from the canvas either with custom code or using GIFSHOT [YES - SOLVED]

### ISSUE THREAD

**Issue by alexbudin** [jeeliz/jeelizFaceFilter#66]
Hey Xavier,

Any way we can create a gif from the canvas either with custom code or using GIFSHOT?

https://github.com/yahoo/gifshot

In its options it has a "cameraStream" option that expects a cameraStream Media object. I tried putting  THREECAMERA as the cameraStream option, but i get the error:

![image](https://user-images.githubusercontent.com/832030/48924057-c4557f80-eebc-11e8-9a0a-e73f573c6791.png)

This is the code:

 gifshot.createGIF({
      'cameraStream': THREECAMERA,
    },function(obj) {
      if(!obj.error) {
        var image = obj.image,
        animatedImage = document.createElement('img');
        animatedImage.src = image;
        document.body.appendChild(animatedImage);
      }
    });

Any advice on this? Or maybe there is another option of GIfShot that i can use.

Thank you so much.

**Comment by alexbudin** [comment]
Should i make a PR for this on the readme? Maybe an example as well?

Alex

**Comment by xavierjs** [comment]
Hello,

It would be great :). I think this information will be perfect here: https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/faceReplacement/gif

Best,
Xavier

**Comment by xavierjs** [comment]
I close the issue since it is solved :).
