### ISSUE TITLE
Texture is not power of two

### ISSUE THREAD

**Issue by alexbudin** [jeeliz/jeelizFaceFilter#67]
This is my code to create a face filter. Its basically a 2D PNG image that gets put on your face. And it works fine, but i get a warning that the texture is not power of two, but it is.

```
const faceFilterCreator = function(properties){
    const faceFilterObj = new THREE.Object3D();
    
    
    const texture = new THREE.TextureLoader().load( properties.faceFilterPNG );
    texture.magFilter = THREE.LinearFilter;
    texture.minFilter = THREE.LinearMipMapLinearFilter;


    const material = new THREE.MeshBasicMaterial({
        map: texture,
        transparent: true
    });
    window.material = material;
    const faceFilterMesh = new THREE.Mesh(new THREE.PlaneGeometry(3, 3), material);
    faceFilterObj.add(faceFilterMesh);
   
    
    return {
        faceFilter: faceFilterObj,
    };
}
```

![image](https://user-images.githubusercontent.com/832030/48924954-fbc92980-eec6-11e8-8640-24091223b6c2.png)

**properties.faceFilterPNG** is basically the path to a PNG file which is 512x512px in size, which is a size power of two. Any idea why i still get this warning?

Thank you.

**Comment by xavierjs** [comment]
Hi,

This problem is not related to FaceFilter but more to THREE.JS.
I think maybe it is your texture is not loaded yet when you use it.
When you create your textureloader you can pass a loadingManager as argument. The loadingmanager can start the rendering loop as soon as all stuffs are loaded.
