### ISSUE TITLE
Can we get only rendering part?

### ISSUE THREAD

**Issue by vbh25** [jeeliz/jeelizFaceFilter#69]
You have written very nice library which takes care of rendering camera preview in proper style on all devices. Is it possible to get only that part i.e. without face detection etc ?

**Comment by vbh25** [comment]
Yes... But without getusermedia.. For example I use getusermedia seperately and pass the stream to jeelizfacefilter..

**Comment by xavierjs** [comment]
You mean the video cropping and converting from VIDEO to WebGLTexture ?

**Comment by vbh25** [comment]
Yes

**Comment by xavierjs** [comment]
You can find most of these parts parts not compressed on JeelizAR repository, in this helper: https://github.com/jeeliz/jeelizAR/blob/master/helpers/JeelizAR8thWallHelper.js

Basically, cropping involve the comparison between aspect ratios of canvas and video to decide if we should crop bottom/top margin or left/right margins.
Texture updating requires to check whether video.currentTime has changed or not (to update only if the video frame has changed).

**Comment by vbh25** [comment]
Ok thanks
