### ISSUE TITLE
JEEFACEFILTERAPI.get_videoDevices and videoSettings.deviceId is not working 

### ISSUE THREAD

**Issue by kezmanh** [jeeliz/jeelizFaceFilter#70]
When I run JEEFACEFILTERAPI.get_videoDevices, it shows error and after I retrieved the device id by my own code, I tried to change camera by setting videoSettings.deviceId, it is not working as expected. Besides, may I know if there are any ways that I can change rear/front camera in mobile anytime?

**Comment by xavierjs** [comment]
You should give a callback func:
```
JEEFACEFILTERAPI.get_videoDevices(function(vd){console.log(vd)})
```
=> 
```
[InputDeviceInfo]
0: InputDeviceInfo {deviceId: "917980531e265896f4172a89381647aff8932361c7fa6e0417edeb432c826817", kind: "videoinput", label: "USB2.0 HD UVC WebCam (04f2:b3fd)", groupId: "930d5ceb2903f8369caaae758465a67c328fae96b33e85d30dd210d837ce8d4a"}
length: 1
__proto__: Array(0)
```
you cannot change front/back camera dynamically.

**Comment by kezmanh** [comment]
@xavierjs I tried the following one and changed different deviceId but seems not working. Always the same camera is showed.

```
function init_faceFilter(videoSettings){
    videoSettings.deviceId = "c78470c45da818e699858ddcb1df936ea0bb56bfd43d90347d8d0152ab54bce8";

  JEEFACEFILTERAPI.init({
       videoSettings: videoSettings,
       .
       .
       .
   });
} 
```

**Comment by xavierjs** [comment]
Then this standard is not well implemented in all browsers.
It may comes from the WebRTC helper intégrated to FaceFilter API.
You can get the webcam video stream by yourself then provide directly the `<video>` element to FaceFilter with:
```
JEEFACEFILTERAPI.init({
       videoSettings: {
          videoElement: <yourVideoElement>
       }
   });
```
like in this demo except that the video does not come from a file.

**Comment by kezmanh** [comment]
finally it is solved by setting a timeout for the start function.
