### ISSUE TITLE
Can we get pose detection part ?

### ISSUE THREAD

**Issue by veetechh** [jeeliz/jeelizFaceFilter#71]
Looking for head pose estimation in javascript, so that we can get roll, pitch & yaw from our own landmark algorithm.

**Comment by xavierjs** [comment]
Hi,

This library provides the roll, pitch and yaw :) . They are called rx, ry, rz (see https://github.com/jeeliz/jeelizFaceFilter#the-detection-state ).

**Comment by veetechh** [comment]
Ohh... Yes :)

**Comment by xavierjs** [comment]
Unlike other face detection library, we don't detect landmarks to then estimate the pose.
The pose is directly output from the neural network, we only stabilize it.
So we don't need solvePnP.

You can get OpenCV SolvePNP function in JS by compiling OpenCV with emscripten.
But it is still heavy (2.5MB of JS...).
If you have a good implementation of SolvePnP in JS I would be very interested :).

I tested this one: https://github.com/adamwhat/snapweb_js/blob/master/js/solvepnp.js but it is not very good.

**Comment by veetechh** [comment]
Okay, thank you.
