### ISSUE TITLE
Choosing json over other formats.

### ISSUE THREAD

**Issue by veetechh** [jeeliz/jeelizFaceFilter#73]
Is there any reason you have used json models in most of the examples in threejs ?
Because converting to json is bit more complicated for obj file having multiple layers. And also the official blender exporter is removed.

**Comment by xavierjs** [comment]
Hi,

This is not a problem with FaceFilter, but only aTHREE.JS.
There is one example using a GLTF model.
The 3D model importation is supposed to be a prerequisite for the use of this library.
THREE.JS provides a lot of importers, their code is very clean, and nice examples. It is then easy to integrate them with FaceFilter using the boilerplates
