### ISSUE TITLE
Any chance to release the unminified sources and model data shape

### ISSUE THREAD

**Issue by ChristopheBougere** [jeeliz/jeelizFaceFilter#77]
**Is your feature request related to a problem? Please describe.**
The source code, as well as the models, are released under Apache 2.0 which is amazing.
However, it's too bad that the code is minified, which prevent the community from resolving bugs or adding new features.
Also, it would be nice to have a simple tutorial on how to make your own model.

**Describe the solution you'd like**
About the source code, having the unminified source code on GitHub would be great so people can submit PRs!
Concerning the models, I'm not asking for the logic nor the data, but detailing the expected data shape would be enough.

**Describe alternatives you've considered**
[face-api](https://github.com/justadudewhohacks/face-api.js) which does not provide the exact same features but is more open source friendly. 

**Additional context**
Your library is still awesome, thanks for releasing it on GitHub 👌

**Comment by xavierjs** [comment]
Hi Christophe,

The deep learning part is not released unminified for some reasons I explain here:
https://github.com/jeeliz/jeelizGlassesVTOWidget/issues/2
Some are specific to the glasses VTO use case, but most of them are shared.

Best,
Xavier

**Comment by ChristopheBougere** [comment]
Hi Xavier,
Thanks for your answer.
I can definitely understand that you don't want to spend too much time doing support on things that are very specific to your toolchain and not standard.
That explains why it is both open source and minified (which is not common).
Have a nice day

**Comment by peterellisjones** [comment]
+1 for source code -- without it errors like this are impossible to debug:

![Screenshot 2020-09-02 at 15 59 22](https://user-images.githubusercontent.com/2788556/92000461-6dd5d000-ed35-11ea-8057-83a7017d5491.png)

**Comment by xavierjs** [comment]
This one is easy, just go in the network tab and you will see that your json is not a json
