### ISSUE TITLE
stabalization code

### ISSUE THREAD

**Issue by rohanmuplara** [jeeliz/jeelizFaceFilter#78]
Hi,
I was wondering hot the internals of your stabilization code worked.  I couldn't figure it out from the minified file.
Thanks,
Rohan

**Comment by xavierjs** [comment]
Hi bro,

There is some doc about how to tweak the stabilization settings in the README.md of this repo but we don't release the source code.
The reasons why the whole source code is not open are explained here:
https://github.com/jeeliz/jeelizGlassesVTOWidget/issues/2
Some are specific to the VTO use case, but many are common with FaceFilter.

Best,
Xavier
