### ISSUE TITLE
Eyes "state" detection (opened/closed)

### ISSUE THREAD

**Issue by hugohil** [jeeliz/jeelizFaceFilter#79]
Hello, and thanks for the lib it's super efficient and easy to use 👍 

I was wondering, do you plan to add eyes expression, in the same way you did with the mouth ?
An opening coefficient, or maybe an open/closed boolean ?

**Comment by xavierjs** [comment]
Hi,
We will do this, but our training slots are busy for the next 3 months for paid jobs and after we still have some stuffs to train.
Currently Weboji lib includes eyes expressions: https://github.com/jeeliz/jeelizWeboji
But there are some training biases, for example if there are some wrinkles around the eyes the neural net consider that eyes are closed. So eyes opening detection is currently not as robust as mouth opening detection. I have still to work on it.

Best,
Xavier

**Comment by hugohil** [comment]
Thanks for the answer, closing the issue then ;)

**Comment by c4b4d4** [comment]
Is there any update on this topic? Is eyes state detection possible atm? 👀

**Comment by xavierjs** [comment]
Hi,

This topic is more than 4 years old, and eyes open/close is not in Jeeliz Facefilter roadmap anymore.
However this feature is implemented in WebAR.rocks.face ( https://github.com/WebAR-rocks/WebAR.rocks.face ), which has an interface quite close to Jeeliz Facefilter.  You can try this demo (included in WebAR.rocks.face github repo): https://webar.rocks/demos/face/demos/expressionsDetection/

Jeeliz Facefilter will be still maintained and improved regularly to keep optimal compatibility coverage.
