### ISSUE TITLE
Allow canvas to be passed by reference

### ISSUE THREAD

**Issue by Joe-Palmer** [jeeliz/jeelizFaceFilter#83]
**Is your feature request related to a problem? Please describe.**
We are building a Web Component that integrates your great project! :) The problem is that all our functionality is encapsulated within a shadow dom so passing a canvas id does not work as it cannot be found in the document as it is actually inside the shadow dom. 

**Describe the solution you'd like**
It would be great if we could pass a reference to the canvas (in the same way as we can pass a reference to `videoElement`) rather than the id so that we can use a canvas within a shadow dom.

**Describe alternatives you've considered**
We have worked around this for now by injecting the canvas into the document but this is not ideal as it bypasses the advantages of shadow dom encapsulation.

**Additional context**
Our Web Component is intended to be embedded into any web page so encapsulation is important to avoid any CSS or JavaScript conflicts with code on the main page.

**Comment by xavierjs** [comment]
You should be able to use `canvas` property instead of `canvasId` property since the last commit of the lib.
Best,
Xavier

**Comment by Joe-Palmer** [comment]
This works great, thanks very much! 👍

**Comment by xavierjs** [comment]
Thank you for having submitted this issue. 
You are welcome to submit a pull request to add the web component, or a link to add to the README.md :).

I close the issue.

Best,
Xavier
