### ISSUE TITLE
Is it possible to use jeelizFaceFilter on a DSLR using gphoto2 (live preview)?

### ISSUE THREAD

**Issue by jedaivokters** [jeeliz/jeelizFaceFilter#84]
I see this https://github.com/jeeliz/jeelizFaceFilter/issues/26 but wonder how can I do it using gphoto2

**Comment by xavierjs** [comment]
I have no idea bro. I think you should use a webgl compatible headless browser. If you figure out how to do this you are welcome to submit a PR :).

**Comment by xavierjs** [comment]
Maybe you could use your camera as a webcam using gphoto2:
http://blog.skhawaja.com/2015/12/use-your-dslr-camera-work-as-webcam-on.html?m=1
Then you can get the video feed in your web browser and use this library.

**Comment by jedaivokters** [comment]
Hi @xavierjs ,

I was thinking if this https://github.com/lwille/node-gphoto2 can do file streaming and render it onto the HTML5 video tag as a source into jeelizFaceFilter

**Comment by xavierjs** [comment]
I think it is doable, but the guys of https://github.com/lwille/node-gphoto2 would be more helpful for that :).

**Comment by jedaivokters** [comment]
Thanks @xavierjs , I'll try to connect with them.

**Comment by xavierjs** [comment]
There are no news about this issue since 22days so I close it. But feel free to reopen it if there is sthing New.
