### ISSUE TITLE
Image filtering instead of video only

### ISSUE THREAD

**Issue by gabrielIV** [jeeliz/jeelizFaceFilter#86]
I'm trying to implement the face filter to images (jpeg images), but I can't find any mention of it anywhere

**Comment by xavierjs** [comment]
take a look at the demo on face replacement. It is done there.

**Comment by gabrielIV** [comment]
Thankyou for the quick response. Is it possible to run the plugin on a machine without a webcam? It doesn't seem to work on browsers that do not detect a webcam.

**Comment by xavierjs** [comment]
Hi
No it is not but we can add this feature as a tailored development service. You can contact us by email for more information about the pricing

Best
Xavier
