### ISSUE TITLE
Pass NN by object (not by URL/string)

### ISSUE THREAD

**Issue by BrowseHandsfree** [jeeliz/jeelizFaceFilter#88]
Thanks for making this project open sourced, I've been working on a similar tool but have since switched to your facefilter because of how incredibly lightweight it is!

**Is your feature request related to a problem? Please describe.**
Because the NN model needs to be loaded through a URL, an extra HTTP request needs to be made to fetch it. This becomes a problem when trying to load facefilter in environments where extra requests cannot be made.

For example, I'm trying to use the facefilter inside of Discourse to browse the forums hands-free (for people with disabilities). Because of the way Discourse bundles assets, you can't actually reference the NN by URI. In other words, this won't work:

```js
facefilter.init({
  canvasId: 'facefilter-canvas',
  NNCpath: ''
})
```

but this would

```js
const model = require('path/to/model.json')
facefilter.init({
  canvasId: 'facefilter-canvas',
  NNModel: model
})
```

**Describe the solution you'd like**
I think we should be able to just pass the model object directly instead of by URI.

**Describe alternatives you've considered**
I could probably base64 encode a URI, but then encoded string would be massive.

**Comment by xavierjs** [comment]
Hi,

Sounds good, I will add this feature very soon, it's not a big deal :)

Best,
Xavier

**Comment by xavierjs** [comment]
It should work:

_It is also possible to give directly the NNC json file content by using NNC property instead of NNCpath._
