### ISSUE TITLE
"AN ERROR HAPPENS. ERR = ALREADY_INITIALIZED"

### ISSUE THREAD

**Issue by germanbisurgi** [jeeliz/jeelizFaceFilter#89]
**Describe the bug**
Cann not destroy the instance. I always get:
 "AN ERROR HAPPENS. ERR = ALREADY_INITIALIZED"

**To Reproduce**
Just call twice a function that stars the FaceFilter

**Expected behavior**
1 be able to destroy the api.
2 To not get an error message

**Additional context**
starting a vue component once works. But when i restart it i get the error message. Please help! :)

**Comment by xavierjs** [comment]
Hi,

Unfortunately you cannot call multiple times the init method.
I don't see why you should. I don't want to encourage bad practices.

It is not a problem for me if it does not fit with react/vue/other 6 months hype frontend engine. You can still adapt the react/vue paradigm to this lib. I did this for https://jeeliz.com/sunglasses

Best,
Xaiver

**Comment by germanbisurgi** [comment]
Hi Xavier thanks for your reply,

My idea is to use only one instance and then stop (or destroy) the instance after use to free memory and not to have the callbackTrack being called 60 fps in background.
Also i can get the "spec" only by initializing it and i need it in order to create and reload different models with the JeelizThreejsHelper.

Another thing is that i can not check if the API is ALREADY_INITIALIZED cause the api has only methods and no state properties. Is there a ways to check this?

Thanks in advance

**Comment by xavierjs** [comment]
Hi,

I can add this feature for a customized version of the library.
You can contact me directly at xavier__at__jeeliz.com and I will send you a proposal for this development service.

Best regards,
Xavier
