### ISSUE TITLE
how to import JeelizThreejsHelper ?

### ISSUE THREAD

**Issue by stephanedemotte** [jeeliz/jeelizFaceFilter#90]
Hi, thanks for this great lib !!

We can import Jeeliz with`jeelizFaceFilterES6.js` but how can we import `JeelizThreejsHelper` ?

Thanks !

**Comment by xavierjs** [comment]
Hi

We are still waiting for the good guy who will submit a pull request :)

**Comment by stephanedemotte** [comment]
If someone use vue-cli 

```
const webpack = require('webpack')
module.exports = {
  chainWebpack: (config) => {
    config
      .plugin('provide')
      .use(webpack.ProvidePlugin, [{
        THREE: 'three'
      }])
  }
}
```
