### ISSUE TITLE
Facing an error setting up Glasses VTO Widget.

### ISSUE THREAD

**Issue by mudzz174** [jeeliz/jeelizFaceFilter#91]
I was setting up Glasses VTO Widget by referring this tutorial https://jeeliz.com/blog/vto-studio-lite-tutorial/ and I used same html code as used in tutorial but for accurate knowledge of problem I added code also i.e: `<!DOCTYPE html>
<html>
    <meta charset='utf-8'>
    <head>
        <title>MY VTO WIDGET</title>
        <script type="text/javascript" src="JeelizWidgetVTO.js"></script>
        <style>
        </style>
    </head>
    <body>
        <canvas width="800" height="600" id="jeelizWidgetVTOCanvas"></canvas>
        <button onclick="VTOStudio.main()">Click to start the widget</button>
    </body>
</html>`
My js file generated by VTO studio lite is [https://we.tl/t-WGoy8EtTDj]
And I faced this error 
![error](https://user-images.githubusercontent.com/48759407/54897792-dc332380-4eef-11e9-83f8-03e6b1a8ae6c.png)

I am not a good technical person so if you please help me resolve it by a decent manner, it would be great.

**Comment by xavierjs** [comment]
Your issue is not understandable.
