### ISSUE TITLE
Tracking only mode?

### ISSUE THREAD

**Issue by Joe-Palmer** [jeeliz/jeelizFaceFilter#92]
**Is your feature request related to a problem? Please describe.**
We have been working on integrating your great face detection and tracking project with our project and have hit a snag. We make heavy use of WebGL to apply filters to the camera stream and when we run your face detector in parallel, it can take over 10 seconds to find a face. Having done some analysis on this, here are our findings:

- Our process is running the GPU at maximum using requestAnimationFrame
- Face detection is really slow but tracking seems to work OK
- Throttling our process to 30 fps helps a bit, but not enough
- Disabling `toggle_slow` also helps but makes the UI laggy
- It appears that your face detection is much more heavyweight then the tracking

**Describe alternatives you've considered**
We have had to look for alternatives as it is important for us that the face detection starts as soon as possible. We have found [PicoJS](https://github.com/tehnokv/picojs) which can use the [pico framework](https://github.com/nenadmarkus/pico) as a [WASM module for face detection](https://demos.tkv.io/pico-to-wasm/) and it is incredibly quick! But it does not give us any feature points or pose detection which we would really like.

**Describe the solution you'd like**
We were wondering if it would be feasible to have a tracking only mode where we could pass in a bounding box of the user's face and just use your library for face tracking and pose estimation. This would allow us to use Pico WASM for super fast face detection and jeelizFaceFilter for rich face information. Do you think that would be possible?

**Additional context**
I would be happy to work on a PR for this feature but that would not be feasible with minified code.

Let me know your thoughts on this.

Thanks :)

**Comment by blurymind** [comment]
I just want to add that I also use the library only for tracking - the rotation of the head. All the threejs stuff is of no use to me, nor is showing the webcamera.  Getting the input is enough.

I am also throttling the input in order to reduce strain on the cpu - using another js library.

One thing that would help is being able to pause/unpause the tracking easily.

**Comment by xavierjs** [comment]
Hi,

Indeed, these features are not currently implemented in this Github repository.
But it is outside the scope of this library (FaceFilter with external 3D engine).

However, I would be happy to help you to adapt our libraries to fit your needs.
You can contact me directly at xavier__at__jeeliz.com and I will send you a proposal for this development service.

Best regards,
Xavier
