### ISSUE TITLE
How to create NNC.JSon Model?

### ISSUE THREAD

**Issue by sandhyacs** [jeeliz/jeelizFaceFilter#94]
Thank you for creating such a nice web api for real time application. I want to know the procedure how you are creating NNC.json model.

**Comment by xavierjs** [comment]
Hi,

Unfortunately it is not possible. Some reasons are explained here: https://github.com/jeeliz/jeelizGlassesVTOWidget/issues/2

But we can provide development and neural network training services, you can contact us here: https://jeeliz.com/contact-us/

Best,
Xavier
