### ISSUE TITLE
Blank screen in Chrome on iOS (12.2)

### ISSUE THREAD

**Issue by viperphase1** [jeeliz/jeelizFaceFilter#95]
**Describe the bug**
None of the demos appear to be working on Chrome on iOS (tested on iOS 12.2). Which probably means that any project using jeeliz face filter isn't going to work on iOS Chrome either. The face filter fails before it is able to open the camera feed. I don't have the tools to remotely debug iOS Chrome so I can't narrow it down any more than that. I don't see this issue in here yet so I thought I would bring it up.

**Comment by xavierjs** [comment]
On IOS Chrome is only a webview of safari.
And Safari webviews camera does not give access to the camera.

I close the issue since it is not a problem with FaceFilter, but with this crappy OS. Just catch the error and ask the user to display using Safari.

**Comment by viperphase1** [comment]
Good to know, thanks.

**Comment by xavierjs** [comment]
Related to https://github.com/jeeliz/jeelizWeboji/issues/27

**Comment by xavierjs** [comment]
**BREAKING NEWS**: Camera access is enabled on IOS14.3 which is released this Monday ( December 14th ). So FaceFilter will work on Chrome, Firefox, Opera for IOS, and into `WKWebviews` embedded in native apps.
