### ISSUE TITLE
Canvas video stream freezes on mobile safari [IOS (12.2)]

### ISSUE THREAD

**Issue by bhargavkuchipudi** [jeeliz/jeelizFaceFilter#96]
**Describe the bug**
1. I have two iPhone 6S one was running on **12.1.4** and the other was running on **12.2**.
    when I try to open my application(jeeliz integrated) it's working fine on **12.1.4** but, on 
    **12.2** the frame is freezing after taking the first frame.
2. video was not in a square on the canvas. it is getting trimmed on sides.
3. The detection is very slow and sometimes the square gets struck.
4. When we debug safari mobile (IOS 12.2) we are getting this error **WebGL: INVALID_OPERATION: texImage2D: type HALF_FLOAT_OES but ArrayBufferView is not NULL**

**To Reproduce**
1. Go to safari (IOS 12.2)
2. Click on [this link](https://jeeliz.com/demos/faceFilter/demos/canvas2D/faceTrack/)
3. You can find that video is trimmed on sides

![IMG_1459](https://user-images.githubusercontent.com/39960735/55874307-980e7700-5baf-11e9-9fe2-751101638f19.PNG)

**Comment by xavierjs** [comment]
I am tired of solving IOS problems because Apple is not able to implement a standard correctly.
Just dig out yourself, or post the issue where it should be: on IOS support.

Best,
Xavier

**Comment by xavierjs** [comment]
Duplicate of #14
