### ISSUE TITLE
FaceFilterLM progress

### ISSUE THREAD

**Issue by whilemouse** [jeeliz/jeelizFaceFilter#97]
Hi. I'm using your library to make it useful. thanks.

I did asked [FaceFilterLM](https://github.com/jeeliz/jeelizFaceFilter/issues/60).

> FaceFilter will be improved in the next few months (I know this is possible to get a better positionning)
We are going to release FaceFilterLM, which is a landmark based version of facefilter.
The positionning will be more accurate since it uses precise facial landmark (around the ears if the user is rotating the head left<->right) and we hope to propose a very good VTO solution with an integration sample with THREE.JS. The library will not be free, but its cost will be lower than elsewhere and there will be FaceFilter bindings (so an app working with facefilter will be quickly adapted to FaceFilterLM).

I'm looking forward to this. :)
If this is in progress, when can I try it?

**Comment by xavierjs** [comment]
Hi,

The project is currently paused, since we are currently providing research & development services for AR. There are still some interesting results, but no release yet.

Best,
Xavier

**Comment by whilemouse** [comment]
Thanks. :)
