### ISSUE TITLE
this yours example website is not working https://jeeliz.com/sunglasses/

### ISSUE THREAD

**Issue by tarasprystavskyj** [jeeliz/jeelizFaceFilter#98]
**Describe the bug**
The feature of selecting a picture as a source on the example website is not working https://jeeliz.com/sunglasses/

I suppose the reason is that some remote resource code is not accessible any more 
http://prntscr.com/nest4x
as this service domain is not accessible at all fallbackglassesdb.jeeliz.com

**To Reproduce**
Try to pic an external face picture as a source file 
We get this http://prntscr.com/nesusu
![change source not working](https://user-images.githubusercontent.com/7785635/56466958-92bbf280-6421-11e9-8fa9-064bbb909e6e.png)
![console error](https://user-images.githubusercontent.com/7785635/56466966-a8c9b300-6421-11e9-8c7d-8d29e043d379.png)

**Expected behavior**
It should show glasses over my face picture

**Screenshots**
http://prntscr.com/nesusu

**Desktop (please complete the following information):**
 - OS: windows7
 - Browser chrome
 - Version 73

**Smartphone (please complete the following information):**
not tested, suppose result will be the same 

**Additional context**

**Comment by xavierjs** [comment]
Hi,

Thanx for this report, the server-side fallback rendering server was down. It has been restarted.

Best,
Xavier
