### ISSUE TITLE
How to use this with Angular Project.

### ISSUE THREAD

**Issue by ramprakashram** [jeeliz/jeelizFaceFilter#99]
I am trying to create face filter for my Angular application. But i am not sure how to use this. As it is not an npm, can you please help me in using this filter in my application.

**Comment by xavierjs** [comment]
I don't work with Angular, so I don't know neither. It is also out of the scope of our support, since it concerns more Angular than Jeeliz FaceFilter. If you managed to nail it, you are welcome to submit your solution here or submit a PR since it may help other users.

**Comment by xavierjs** [comment]
Hi,
This guy seems to have done an Angular integration: https://github.com/nickydev100/FFMpeg-Angular-Face-Filter
Best,
Xavier

**Comment by xavierjs** [comment]
Hi,

This is another Angular integration, for Jeeliz Weboji (but still similar): https://github.com/JeffWinder/jeelizWeboji-angular-electron-example

Best,
Xavier
